/**
 * Factory findings triage tests (voicebox-beads-h1u0).
 *
 * The fixtures in `tests/fixtures/factory-reports/` were generated by the factory's OWN renderer
 * (`lib/findings.py:_render_delta_report`), not written by hand — a hand-written fixture would
 * only prove the parser agrees with the test author's idea of the format. Regeneration is
 * documented in `tests/fixtures/factory-reports/README.md`.
 *
 * The tests are pure: no network, no model, no real `bd`. The apply path runs against a stub
 * `bd` on PATH, because a test that files beads into the project board is a test that changes the
 * board.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, cpSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  BEAD_EXTERNAL_REF_PREFIX,
  CREDENTIAL_AGENTS,
  EMBARGOED_SEVERITIES,
  IDENTITY_CRITICAL_AGENTS,
  STATION_CLASSES,
  VALID_SEVERITIES,
  agentFromReportName,
  buildBead,
  buildPlan,
  computeFingerprint,
  existingBeadFingerprints,
  isDuplicate,
  isInside,
  maskText,
  parseBadge,
  parseReport,
  priorityFor,
  privateRootFromEnv,
  routeFinding,
  sanitizeFinding,
  suggestsFunctionalityChange,
} from "../scripts/factory-triage.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SCRIPT = join(ROOT, "scripts", "factory-triage.mjs");
const FIXTURES = join(HERE, "fixtures", "factory-reports");

const fixture = (name) => readFileSync(join(FIXTURES, name), "utf8");
const parseFixture = (name, agent) => parseReport(fixture(name), { agent });

/** Run the CLI in a private temp dir, with an optional stub `bd` on PATH. */
function runCli({ args, reports = {}, stubBd = null, cwd = null }) {
  const box = mkdtempSync(join(tmpdir(), "factory-triage-"));
  const privateDir = join(box, "private");
  mkdirSync(privateDir);
  for (const [name, contents] of Object.entries(reports)) writeFileSync(join(privateDir, name), contents);
  const logFile = join(box, "bd-calls.log");
  const bin = join(box, "bin");
  if (stubBd) {
    mkdirSync(bin);
    writeFileSync(
      join(bin, "bd"),
      `#!/bin/sh\nprintf '%s\\n' "$*" | tr '\\n' ' ' >> ${logFile}\nprintf '\\n' >> ${logFile}\n${stubBd}\n`,
    );
    chmodSync(join(bin, "bd"), 0o755);
  }
  const repo = cwd ?? join(box, "repo");
  mkdirSync(repo, { recursive: true });
  // `%PRIVATE%` lets a test address the private dir it cannot know before the call.
  const resolvedArgs = args.map((arg) => (arg === "%PRIVATE%" ? privateDir : arg));
  const res = spawnSync(process.execPath, [SCRIPT, ...resolvedArgs], {
    cwd: repo,
    encoding: "utf8",
    timeout: 60000,
    env: {
      ...process.env,
      PATH: stubBd ? `${bin}:${process.env.PATH}` : process.env.PATH,
      VOICEBOX_FACTORY_PRIVATE_DIR: privateDir,
    },
  });
  return {
    ...res,
    box,
    repo,
    privateDir,
    bdCalls: existsSync(logFile) ? readFileSync(logFile, "utf8").trim().split("\n").filter(Boolean) : [],
  };
}

// ---------------------------------------------------------------------------------------------
// Mirrored policy constants
// ---------------------------------------------------------------------------------------------

test("mirrored policy constants match the factory's published values", () => {
  assert.deepEqual([...IDENTITY_CRITICAL_AGENTS].sort(), [
    "secret-scan",
    "threat-model",
    "vuln-discovery",
    "vuln-triage",
    "vuln-verify",
  ]);
  assert.deepEqual([...CREDENTIAL_AGENTS], ["secret-scan"]);
  assert.deepEqual([...VALID_SEVERITIES], ["critical", "high", "medium", "low", "info"]);
  assert.deepEqual([...EMBARGOED_SEVERITIES].sort(), ["critical", "high"]);
  assert.equal(BEAD_EXTERNAL_REF_PREFIX, "factory:");
  // Every station `factory list` reports has a class, or a bead body says "quality" for it.
  for (const station of Object.keys(STATION_CLASSES)) {
    assert.match(station, /^[a-z0-9-]+$/);
  }
});

// ---------------------------------------------------------------------------------------------
// Fingerprint: the mirror of lib/findings.py must be exact, or dedupe silently breaks
// ---------------------------------------------------------------------------------------------

test("computeFingerprint reproduces the factory's fingerprints for every real fixture", () => {
  let checked = 0;
  for (const name of readdirSync(FIXTURES).filter((n) => n.endsWith("-delta.md"))) {
    const agent = agentFromReportName(name);
    const report = parseFixture(name, agent);
    for (const finding of report.findings) {
      if (finding.identitySource === "unverifiable") continue; // reduced form carries no snippet
      assert.equal(
        finding.identitySource,
        "recomputed-and-verified",
        `${name}: recomputed fingerprint ${finding.fingerprint} does not match the report prefix ${finding.fingerprintFromReport}`,
      );
      checked += 1;
    }
  }
  assert.ok(checked >= 4, `expected to verify several fingerprints, checked ${checked}`);
});

test("normalization follows lib/findings.py: path separators and whitespace collapse", () => {
  // normalize_path: backslashes to forward, strip, lstrip('./'); normalize_text: collapse spaces.
  const a = computeFingerprint({ agent: "a", ruleId: "r", path: "./src\\x.ts", snippet: "  one   two\n" });
  const b = computeFingerprint({ agent: "a", ruleId: "r", path: "src/x.ts", snippet: "one two" });
  assert.equal(a, b);
});

test("a recomputed fingerprint that disagrees with the report prefix is deferred, never filed", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const tampered = { ...finding, fingerprintFromReport: "0".repeat(16), identitySource: "recomputed-mismatch" };
  const verdict = routeFinding(tampered);
  assert.equal(verdict.action, "defer");
  assert.match(verdict.reasons[0], /identity mismatch/);
  assert.equal(buildBead(tampered, verdict, {}).fingerprint === undefined, false);
});

// ---------------------------------------------------------------------------------------------
// Severity mapping: fail-closed, identity before the model's label
// ---------------------------------------------------------------------------------------------

test("parseBadge understands both badge forms, including the routed elevation", () => {
  assert.deepEqual(parseBadge("MEDIUM"), { reported: "medium" });
  assert.deepEqual(parseBadge("HIGH · routed critical"), { reported: "high", routed: "critical" });
  assert.deepEqual(parseBadge("FALSE POSITIVE"), { falsePositive: true });
});

test("severity is fail-closed: an unknown or missing label is critical, never medium", () => {
  // Driven through the parser, not asserted on a value this test computed: a badge the factory
  // does not recognise must land as `critical` in the parsed finding itself.
  const fixtureText = fixture("voicebox-qa-station-delta.md");
  for (const badge of ["SEVERE", "IMPORTANT", "MEDUM", "5"]) {
    const rewritten = fixtureText.replace("[MEDIUM]", `[${badge}]`);
    assert.notEqual(rewritten, fixtureText, "the badge rewrite must apply");
    const [finding] = parseReport(rewritten, { agent: "qa-station" }).findings;
    assert.equal(finding.severityReported, badge.toLowerCase());
    assert.equal(
      finding.effectiveSeverity,
      "critical",
      `badge ${badge} must fail closed to critical, got ${finding.effectiveSeverity}`,
    );
    assert.equal(routeFinding(finding).action, "defer");
  }
});

test("an identity-critical station is elevated here even without the factory's routed badge", () => {
  // The factory already routes `secret-scan` to critical, so its badge usually says `routed
  // critical`. This removes that crutch: the backstop must hold on a plain `[MEDIUM]` too,
  // because a station that understates a credential is exactly the case this mirrors.
  const rewritten = fixture("voicebox-secret-scan-delta.md").replace("[MEDIUM · routed critical]", "[MEDIUM]");
  assert.match(rewritten, /\[MEDIUM\]/);
  const [finding] = parseReport(rewritten, { agent: "secret-scan" }).findings;
  assert.equal(finding.severityRouted, null);
  assert.equal(finding.identityCritical, true);
  assert.equal(finding.effectiveSeverity, "critical");
  assert.equal(routeFinding(finding).action, "defer");
});

test("an identity-critical station elevates a medium label to critical (routing, not display)", () => {
  const [finding] = parseFixture("voicebox-secret-scan-delta.md", "secret-scan").findings;
  assert.equal(finding.severityReported, "medium");
  assert.equal(finding.severityRouted, "critical");
  assert.equal(finding.effectiveSeverity, "critical");
  assert.equal(finding.identityCritical, true);
  const verdict = routeFinding(finding);
  assert.equal(verdict.action, "defer");
  // The identity rule is what the human reads in the reason, so losing it is a real regression
  // even though the decision itself comes from the severity band.
  assert.match(verdict.reasons[0], /identity-critical agent `secret-scan`/);
});

test("the publishable band maps to priority; embargoed bands never reach the board", () => {
  const medium = { effectiveSeverity: "medium" };
  const high = { effectiveSeverity: "high" };
  const critical = { effectiveSeverity: "critical" };
  const low = { effectiveSeverity: "low" };
  assert.equal(priorityFor(medium), 2);
  assert.equal(priorityFor(high), 1);
  assert.equal(priorityFor(critical), 1);
  assert.equal(priorityFor(low), 3);
});

test("a high finding from a non-sensitive station is filed sanitised at P1; the same from a sensitive one is deferred", () => {
  const [perf] = parseFixture("voicebox-perf-review-delta.md", "perf-review").findings;
  assert.equal(perf.effectiveSeverity, "high");
  assert.equal(perf.identityCritical, false);
  const verdict = routeFinding(perf);
  assert.equal(verdict.action, "file");
  assert.equal(priorityFor(perf), 1);

  const sensitive = { ...perf, agent: "vuln-verify", identityCritical: true, effectiveSeverity: "critical" };
  assert.equal(routeFinding(sensitive).action, "defer");
});

test("low and info findings are below the board band unless --include-low is given", () => {
  const [low] = parseFixture("voicebox-modern-web-delta.md", "modern-web").findings;
  assert.equal(low.effectiveSeverity, "low");
  assert.equal(routeFinding(low).action, "skip");
  assert.equal(routeFinding(low, { includeLow: true }).action, "file");
  const info = { ...low, effectiveSeverity: "info" };
  assert.equal(routeFinding(info).action, "skip");
  assert.equal(routeFinding(info, { includeLow: true }).action, "file");
});

// ---------------------------------------------------------------------------------------------
// Sanitisation: a credential must not reach a bead body, whatever the model echoed
// ---------------------------------------------------------------------------------------------

test("every credential shape the factory masks is masked here too", () => {
  // Shapes are built at runtime so no realistic-looking token is committed to the repository.
  const shapes = [
    `sk-${"A".repeat(24)}`,
    `sk_live_${"B".repeat(24)}`,
    `AIza${"C".repeat(35)}`,
    `ya29.${"D".repeat(24)}`,
    `glpat-${"E".repeat(24)}`,
    `npm_${"F".repeat(36)}`,
    `ghp_${"G".repeat(36)}`,
    `xoxb-1234567890-1234567890-abcdef`,
    `ey${"H".repeat(12)}.ey${"I".repeat(12)}.${"J".repeat(12)}`,
    `api_key: "${"K".repeat(32)}"`,
  ];
  for (const value of shapes) {
    const masked = maskText(`prefix ${value} suffix`);
    assert.ok(!masked.includes(value), `${value.slice(0, 12)}… survived masking: ${masked}`);
    assert.match(masked, /\[redacted:[a-z-]+\]/);
  }
  const pem = "-----BEGIN RSA PRIVATE KEY-----\nMIIabc\n-----END RSA PRIVATE KEY-----";
  assert.ok(!maskText(pem).includes("MIIabc"));
});

test("a credential-class station's snippet is withheld wholesale, not merely masked", () => {
  const [finding] = parseFixture("voicebox-secret-scan-delta.md", "secret-scan").findings;
  const sanitized = sanitizeFinding(finding, { privateRoot: "/private/reports" });
  assert.equal(sanitized.snippet.startsWith("[withheld: credential-class agent"), true);
  assert.ok(!sanitized.snippet.includes("CANARY-fixture-not-a-real-credential"));
  const bead = buildBead(finding, routeFinding(finding), { privateRoot: "/private/reports" });
  assert.ok(!bead.description.includes("CANARY-fixture-not-a-real-credential"));
  assert.ok(!bead.title.includes("CANARY-fixture-not-a-real-credential"));
});

test("a canary credential echoed into a description by the model is masked before it is published", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const canary = `sk-${"Z".repeat(24)}`;
  const withEcho = { ...finding, description: `the triage model repeated the value ${canary} in prose` };
  const bead = buildBead(withEcho, routeFinding(withEcho), { privateRoot: "/private/reports" });
  assert.ok(!bead.description.includes(canary), "the echoed credential reached the bead body");
  assert.ok(bead.description.includes("[redacted:"));
});

test("home paths and the private report directory are elided from a bead", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const rooted = {
    ...finding,
    description: `report at /home/operator/.voicebox/factory-reports/x.md and /home/someone-else/tree/y`,
  };
  const bead = buildBead(rooted, routeFinding(rooted), { privateRoot: "/home/operator/.voicebox/factory-reports" });
  assert.ok(!bead.description.includes("/home/operator"), "the private root leaked");
  assert.ok(!bead.description.includes("/home/someone-else"), "another operator's path leaked");
});

// ---------------------------------------------------------------------------------------------
// The private-report boundary
// ---------------------------------------------------------------------------------------------

test("a report inside the repository is refused with exit 1", () => {
  const res = runCli({
    args: ["--report", join(FIXTURES, "voicebox-qa-station-delta.md")],
    cwd: ROOT, // the report must be inside the tree the run considers "the repository"
  });
  assert.equal(res.status, 1, res.stderr);
  assert.match(res.stderr, /inside the repository/);
  assert.equal(res.bdCalls.length, 0);
});

test("the default private root is outside the repository and honours the env override", () => {
  const root = privateRootFromEnv({});
  assert.equal(isInside(join(root, "voicebox-qa-station-delta.md"), ROOT), false);
  assert.equal(privateRootFromEnv({ VOICEBOX_FACTORY_PRIVATE_DIR: "/tmp/explicit" }), "/tmp/explicit");
});

test("a report path that escapes through a symlink is still refused", () => {
  const box = mkdtempSync(join(tmpdir(), "factory-symlink-"));
  const link = join(box, "escape");
  execFileSync("ln", ["-s", join(FIXTURES, "voicebox-qa-station-delta.md"), link]);
  assert.equal(isInside(join(link), ROOT), true);
  const ok = runCli({
    args: ["--report", link],
    cwd: ROOT,
  });
  assert.equal(ok.status, 1, ok.stderr);
  assert.match(ok.stderr, /inside the repository/);
});

// ---------------------------------------------------------------------------------------------
// Plan mode: read-only, exit codes, actionable filtering
// ---------------------------------------------------------------------------------------------

test("plan mode files nothing and writes nothing", () => {
  const res = runCli({
    args: ["--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  assert.equal(res.status, 0, res.stderr);
  assert.match(res.stdout, /\[FILE\] P2 medium qa-station/);
  assert.equal(res.bdCalls.length, 0, `plan mode called bd: ${res.bdCalls.join(" | ")}`);
  assert.deepEqual(readdirSync(res.repo), [], "plan mode wrote into the repository");
});

test("exit code 2 when there is nothing actionable", () => {
  const res = runCli({
    args: ["--report", "voicebox-modern-web-delta.md"],
    reports: { "voicebox-modern-web-delta.md": fixture("voicebox-modern-web-delta.md") },
  });
  assert.equal(res.status, 2, `${res.stdout}\n${res.stderr}`);
  assert.match(res.stdout, /SKIP/);
});

test("exit code 1 on a usage error, and on an unknown station", () => {
  assert.equal(runCli({ args: [] }).status, 1);
  assert.equal(runCli({ args: ["--report", "--apply"] }).status, 1);
  const unknown = runCli({
    args: ["--report", "voicebox-not-a-station-delta.md"],
    reports: { "voicebox-not-a-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  assert.equal(unknown.status, 1);
  assert.match(unknown.stderr, /cannot determine the station/);
  // A station name is never guessed from a split: `--agent` is the explicit escape hatch.
  const explicit = runCli({
    args: ["--agent", "qa-station", "--report", "voicebox-not-a-station-delta.md"],
    reports: { "voicebox-not-a-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  assert.equal(explicit.status, 0, explicit.stderr);
});

test("a station name must come from the report filename or --agent, never a guess", () => {
  assert.equal(agentFromReportName("voicebox-qa-station-delta.md"), "qa-station");
  assert.equal(agentFromReportName("voicebox-test-gap-delta.md"), "test-gap");
  assert.equal(agentFromReportName("voicebox-delta.md"), null);
  assert.equal(agentFromReportName("random.md"), null);
});

test("a hyphenated station name is read whole, not split on the last hyphen", () => {
  // `voicebox-docs-drift-delta.md` split greedily is station `drift`; that name is not a station
  // at all, and `voicebox-vuln-discovery-delta.md` would lose its security class.
  assert.equal(agentFromReportName("voicebox-docs-drift-delta.md"), "docs-drift");
  assert.equal(agentFromReportName("voicebox-vuln-discovery-delta.md"), "vuln-discovery");
  assert.equal(agentFromReportName("voicebox-deps-supply-chain-delta.md"), "deps-supply-chain");
  assert.equal(agentFromReportName("voicebox-threat-model-delta.md"), "threat-model");
  assert.equal(agentFromReportName("voicebox-qa-station-delta.md"), "qa-station");
  assert.equal(agentFromReportName("reports/docs-drift-delta.md"), "docs-drift");
});

test("a bare report name resolves inside the private root, not the working directory", () => {
  const res = runCli({
    args: ["--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  assert.equal(res.status, 0, res.stderr);
  assert.match(res.stdout, /\[FILE\] P2/);
});

test("every finding from every real fixture gets a verdict, and the shapes are the ones measured", () => {
  const plan = buildPlan(
    readdirSync(FIXTURES)
      .filter((n) => n.endsWith("-delta.md"))
      .map((n) => join(FIXTURES, n)),
    { privateRoot: "/private", includeLow: false, functionality: new Set() },
  );
  const byAgent = Object.fromEntries(plan.map((entry) => [`${entry.finding.agent}:${entry.finding.ruleId}`, entry.verdict.action]));
  assert.equal(byAgent["qa-station:flake-instrumentation"], "file");
  assert.equal(byAgent["secret-scan:generic-api-key"], "defer");
  assert.equal(byAgent["perf-review:blocking-boot-probe"], "file");
  assert.equal(byAgent["docs-drift:stale-route-table"], "file");
  assert.equal(byAgent["modern-web:legacy-light-dismiss"], "skip");
  // The vuln-discovery fixture is a reduced (step-summary) report: no snippet, no identity.
  assert.equal(byAgent["vuln-discovery:path-traversal"], "defer");
  const reduced = plan.find((entry) => entry.finding.agent === "vuln-discovery");
  assert.equal(reduced.finding.identitySource, "unverifiable");
  assert.equal(reduced.finding.ruleId, "path-traversal", "the rule id lives in the heading in the reduced form");
  assert.equal(reduced.finding.effectiveSeverity, "critical", "vuln-discovery is identity-critical");
});

// ---------------------------------------------------------------------------------------------
// Functionality changes: BLOCKED + human-review, never an auto-fix
// ---------------------------------------------------------------------------------------------

test("a functionality-changing remediation is filed BLOCKED with human-review and one decision", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const changing = { ...finding, remediation: "Rename the route and change the default behaviour" };
  assert.equal(suggestsFunctionalityChange(changing), true);
  const verdict = routeFinding(changing);
  assert.equal(verdict.action, "blocked");
  const bead = buildBead(changing, verdict, { privateRoot: "/private" });
  assert.ok(bead.labels.includes("human-review"));
  assert.match(bead.description, /Decision needed: confirm whether to change this behaviour/);
});

test("the analyst can confirm a functionality change that the hint would miss", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  assert.equal(suggestsFunctionalityChange(finding), false);
  assert.equal(routeFinding(finding).action, "file");
  assert.equal(routeFinding(finding, { confirmedFunctionalityChange: true }).action, "blocked");
});

test("the script itself never writes code: a plan and an apply touch no source file", () => {
  const res = runCli({
    args: ["--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  assert.deepEqual(readdirSync(res.repo), []);
  // The only writes the script can make are beads and the private escalation log.
  const source = readFileSync(SCRIPT, "utf8");
  for (const forbidden of ["writeFileSync", "unlinkSync", "renameSync", "rmSync", "cpSync"]) {
    assert.ok(!source.includes(forbidden), `the script must not ${forbidden}`);
  }
});

// ---------------------------------------------------------------------------------------------
// Apply path: dedupe against the board, mirroring the factory's beads sink
// ---------------------------------------------------------------------------------------------

const LIST_EMPTY = `JSON.stringify([])`;

test("--apply creates one bead with the factory's external-ref convention and dedupes on the next run", () => {
  const res = runCli({
    args: ["--apply", "--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    stubBd: `case "$1" in
      list) echo '[]' ;;
      create) echo "voicebox-beads-created"; ;;
    esac`,
  });
  assert.equal(res.status, 0, res.stderr);
  const create = res.bdCalls.find((call) => call.startsWith("create"));
  assert.ok(create, `no create call: ${res.bdCalls.join(" | ")}`);
  assert.match(create, /--external-ref factory:[0-9a-f]{64}/);
  assert.match(create, /--priority 2/);
  assert.match(create, /--labels factory,station:qa-station,class:quality/);
  assert.match(res.stdout, /filed: [0-9a-f]{16} -> voicebox-beads-created/);

  // A second run against a board that already has the bead must not duplicate it.
  const fp = computeFingerprint({
    agent: "qa-station",
    ruleId: "flake-instrumentation",
    path: "tests/room-folders.test.mjs",
    snippet: 'await page.waitForSelector("text=Projects")',
  });
  const second = runCli({
    args: ["--apply", "--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    stubBd: `case "$1" in
      list) echo '[{"id":"voicebox-beads-existing","status":"open","external_ref":"factory:${fp}"}]' ;;
      create) echo "SHOULD-NOT-BE-CREATED" ;;
    esac`,
  });
  // Nothing actionable on the second run: already tracked, so exit 2 rather than a false "filed".
  assert.equal(second.status, 2, second.stderr);
  assert.equal(second.bdCalls.some((call) => call.startsWith("create")), false, "a duplicate was filed");
  assert.match(second.stdout, /duplicate/);
});

test("a closed bead does not block a regression, but does block an unchanged finding", () => {
  const fingerprint = "a".repeat(64);
  const existing = new Map([[fingerprint, [{ id: "voicebox-beads-old", status: "closed" }]]]);
  assert.equal(isDuplicate({ fingerprint, state: "new" }, existing).ids[0], "voicebox-beads-old");
  assert.equal(isDuplicate({ fingerprint, state: "regressed" }, existing), null);
  const open = new Map([[fingerprint, [{ id: "voicebox-beads-live", status: "in_progress" }]]]);
  assert.equal(isDuplicate({ fingerprint, state: "regressed" }, open).why, "open bead already tracks it");
});

test("the fingerprint can be read back from a bead description when external_ref is absent", () => {
  const fp = computeFingerprint({ agent: "qa-station", ruleId: "r", path: "p", snippet: "s" });
  const index = existingBeadFingerprints("/tmp", {
    run: () => ({ status: 0, stdout: JSON.stringify([{ id: "voicebox-beads-x", status: "open", description: `Fingerprint: ${fp}` }]) }),
  });
  assert.deepEqual(index.get(fp), [{ id: "voicebox-beads-x", status: "open" }]);
});

test("an unreadable board files nothing: the run refuses rather than risking duplicates", () => {
  const res = runCli({
    args: ["--apply", "--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    stubBd: `case "$1" in
      list) exit 1 ;;
      create) echo "SHOULD-NOT-BE-CREATED" ;;
    esac`,
  });
  assert.equal(res.status, 1);
  assert.match(res.stderr, /could not list existing beads/);
  assert.equal(res.bdCalls.some((call) => call.startsWith("create")), false);
});

test("--apply writes deferred findings to a private escalation log and files no bead for them", () => {
  const res = runCli({
    args: ["--apply", "--report", "voicebox-secret-scan-delta.md"],
    reports: { "voicebox-secret-scan-delta.md": fixture("voicebox-secret-scan-delta.md") },
    stubBd: `case "$1" in
      list) echo '[]' ;;
      create) echo "SHOULD-NOT-BE-CREATED" ;;
    esac`,
  });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(res.bdCalls.some((call) => call.startsWith("create")), false, "a deferred finding was filed");
  const log = readFileSync(join(res.privateDir, "escalations.jsonl"), "utf8").trim().split("\n").map((l) => JSON.parse(l));
  assert.equal(log.length, 1);
  assert.equal(log[0].agent, "secret-scan");
  assert.equal(log[0].severity, "critical");
  assert.match(log[0].snippet, /CANARY-fixture/, "the private escalation keeps the evidence a responder needs");
});

test("--apply files a functionality change BLOCKED with a decision comment", () => {
  const report = fixture("voicebox-qa-station-delta.md").replace(
    "Assert on the folder count instead of waiting for a chip",
    "Rename the folder route and change the default behaviour",
  );
  const res = runCli({
    args: ["--apply", "--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": report },
    stubBd: `case "$1" in
      list) echo '[]' ;;
      create) echo "voicebox-beads-blocked" ;;
      update) : ;;
      comment) : ;;
    esac`,
  });
  assert.equal(res.status, 0, res.stderr);
  assert.ok(res.bdCalls.some((call) => /^update voicebox-beads-blocked --status blocked/.test(call)), res.bdCalls.join(" | "));
  assert.ok(res.bdCalls.some((call) => /^comment voicebox-beads-blocked/.test(call)));
  const create = res.bdCalls.find((call) => call.startsWith("create"));
  assert.match(create, /--labels [^ ]*human-review/);
});

test("--json emits the plan without filing anything", () => {
  const res = runCli({
    args: ["--json", "--report", "voicebox-docs-drift-delta.md"],
    reports: { "voicebox-docs-drift-delta.md": fixture("voicebox-docs-drift-delta.md") },
  });
  assert.equal(res.status, 0, res.stderr);
  const plan = JSON.parse(res.stdout);
  assert.equal(plan.length, 1, "the false positive and unchanged findings must not appear as findings");
  assert.equal(plan[0].action, "file");
  assert.equal(plan[0].finding.fingerprint.length, 64);
  assert.equal(plan[0].finding.identity_source, "recomputed-and-verified");
  assert.equal(res.bdCalls.length, 0);
});

test("a directory of reports is triaged in one run", () => {
  const names = readdirSync(FIXTURES).filter((n) => n.endsWith("-delta.md"));
  const reports = Object.fromEntries(names.map((n) => [n, fixture(n)]));
  const res = runCli({ args: ["--report-dir", "%PRIVATE%"], reports });
  assert.equal(res.status, 0, res.stderr);
  for (const name of names) assert.match(res.stdout, new RegExp(name.replace(/[.]/g, "\\.")));
});
