/**
 * Factory findings triage tests (voicebox-beads-h1u0).
 *
 * The fixtures in `tests/fixtures/factory-reports/` were generated by the factory's OWN renderer
 * (`lib/findings.py:_render_delta_report`), not written by hand — a hand-written fixture would
 * only prove the parser agrees with the test author's idea of the format.
 *
 * The tests are pure: no network, no model, no real `gh`, no real `bd`. Both tools are stubbed
 * as executable shell scripts prepended to PATH, logging one line per invocation with newlines
 * flattened.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir, tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  BEAD_EXTERNAL_REF_PREFIX,
  CREDENTIAL_AGENTS,
  CREDENTIAL_RULE_HINTS,
  EMBARGOED_SEVERITIES,
  GENERIC_REMEDIATION,
  IDENTITY_CRITICAL_AGENTS,
  PUBLICATION_DECLARATION,
  STATION_CLASSES,
  VALID_SEVERITIES,
  WITHHELD_NOTE,
  agentFromReportName,
  beadForPromotion,
  buildIssue,
  buildPlan,
  chooseLabels,
  computeFingerprint,
  existingBeadFingerprints,
  existingIssues,
  isCredentialFinding,
  isInside,
  isIssueDuplicate,
  knownLabels,
  markerFor,
  maskText,
  normalizePath,
  normalizeText,
  parseBadge,
  parseMarkers,
  parseReport,
  priorityFor,
  privateRootFromEnv,
  readIssue,
  resolveReportPath,
  routeFinding,
  sanitizeFinding,
  suggestsFunctionalityChange,
} from "../scripts/factory-triage.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SCRIPT = join(ROOT, "scripts", "factory-triage.mjs");
const FIXTURES = join(HERE, "fixtures", "factory-reports");

const fixture = (name) => readFileSync(join(FIXTURES, name), "utf8");
const parseFixture = (name, agent) => parseReport(fixture(name), { agent });

/** Run the CLI in a private temp dir, with stub `gh` and `bd` on PATH. */
function runCli({ args, reports = {}, stubGh = null, stubBd = null, cwd = null, env = {} }) {
  const box = mkdtempSync(join(tmpdir(), "factory-triage-test-"));
  const privateDir = join(box, "private");
  mkdirSync(privateDir, { recursive: true });
  for (const [name, contents] of Object.entries(reports)) {
    writeFileSync(join(privateDir, name), contents);
  }
  const bin = join(box, "bin");
  mkdirSync(bin, { recursive: true });
  const ghLogFile = join(box, "gh-calls.log");
  const bdLogFile = join(box, "bd-calls.log");

  const defaultStubGh = `case "$1" in
    issue)
      case "$2" in
        list) echo '[]' ;;
        create) echo "https://github.com/owner/voicebox/issues/100" ;;
        view) cat << 'EOF'
{"number": 100, "state": "OPEN", "title": "stub", "body": "<!-- factory-fingerprint: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef -->\\n<!-- factory-station: qa-station -->\\n<!-- factory-severity: medium -->\\n<!-- factory-state: new -->\\n**Rule**: \`flake-instrumentation\`", "comments": []}
EOF
        ;;
        comment) echo "https://github.com/owner/voicebox/issues/100#issuecomment-1" ;;
        *) echo "unknown issue subcmd: $2" >&2; exit 1 ;;
      esac
      ;;
    label)
      case "$2" in
        list) echo '[{"name":"bug"},{"name":"enhancement"},{"name":"documentation"},{"name":"accessibility"},{"name":"human-review"}]' ;;
        *) echo "unknown label subcmd: $2" >&2; exit 1 ;;
      esac
      ;;
    *) echo "unknown gh cmd: $1" >&2; exit 1 ;;
  esac`;

  const ghScript = `#!/bin/sh
printf '%s\\n' "$*" | tr '\\n' ' ' >> ${ghLogFile}
printf '\\n' >> ${ghLogFile}
${stubGh ?? defaultStubGh}
`;
  writeFileSync(join(bin, "gh"), ghScript);
  chmodSync(join(bin, "gh"), 0o755);

  const defaultStubBd = `case "$1" in
    list) echo '[]' ;;
    create) echo "voicebox-beads-stub1" ;;
    update) echo "updated" ;;
    comment) echo "commented" ;;
    *) echo "unknown bd cmd: $1" >&2; exit 1 ;;
  esac`;

  const bdScript = `#!/bin/sh
printf '%s\\n' "$*" | tr '\\n' ' ' >> ${bdLogFile}
printf '\\n' >> ${bdLogFile}
${stubBd ?? defaultStubBd}
`;
  writeFileSync(join(bin, "bd"), bdScript);
  chmodSync(join(bin, "bd"), 0o755);

  const repo = cwd ?? join(box, "repo");
  mkdirSync(repo, { recursive: true });

  const resolvedArgs = args.map((arg) => (arg === "%PRIVATE%" ? privateDir : arg));
  const childEnv = {
    ...process.env,
    PATH: `${bin}:${process.env.PATH}`,
    VOICEBOX_FACTORY_PRIVATE_DIR: privateDir,
    VOICEBOX_FACTORY_REPO: "owner/voicebox",
    ...env,
  };
  if ("VOICEBOX_FACTORY_REPO" in env && (env.VOICEBOX_FACTORY_REPO === null || env.VOICEBOX_FACTORY_REPO === undefined)) {
    delete childEnv.VOICEBOX_FACTORY_REPO;
  }

  const res = spawnSync(process.execPath, [SCRIPT, ...resolvedArgs], {
    cwd: repo,
    encoding: "utf8",
    timeout: 30000,
    env: childEnv,
  });

  return {
    ...res,
    box,
    repo,
    privateDir,
    ghCalls: existsSync(ghLogFile) ? readFileSync(ghLogFile, "utf8").trim().split("\n").filter(Boolean) : [],
    bdCalls: existsSync(bdLogFile) ? readFileSync(bdLogFile, "utf8").trim().split("\n").filter(Boolean) : [],
  };
}

// ---------------------------------------------------------------------------------------------
// 1. Mirrored policy constants
// ---------------------------------------------------------------------------------------------

test("mirrored policy constants match the factory's published values", () => {
  assert.deepEqual(
    [...IDENTITY_CRITICAL_AGENTS].sort(),
    ["secret-scan", "threat-model", "vuln-discovery", "vuln-triage", "vuln-verify"],
  );
  assert.deepEqual([...CREDENTIAL_AGENTS], ["secret-scan"]);
  assert.deepEqual([...CREDENTIAL_RULE_HINTS], ["key", "secret", "token", "credential", "password", "private"]);
  assert.ok(Object.isFrozen(CREDENTIAL_RULE_HINTS));
  assert.deepEqual([...VALID_SEVERITIES], ["critical", "high", "medium", "low", "info"]);
  assert.ok(Object.isFrozen(VALID_SEVERITIES));
  assert.deepEqual([...EMBARGOED_SEVERITIES].sort(), ["critical", "high"]);
  assert.equal(BEAD_EXTERNAL_REF_PREFIX, "factory:");
  assert.ok(typeof PUBLICATION_DECLARATION === "string" && PUBLICATION_DECLARATION.length > 50);
  assert.ok(typeof WITHHELD_NOTE === "string" && WITHHELD_NOTE.length > 20);
  assert.ok(typeof GENERIC_REMEDIATION === "string" && GENERIC_REMEDIATION.length > 20);

  // 22 stations from `factory list`, grouped into 6 classes
  assert.equal(Object.keys(STATION_CLASSES).length, 22);
  const allowedClasses = new Set(["security", "quality", "docs", "ux", "perf", "ops"]);
  for (const [station, className] of Object.entries(STATION_CLASSES)) {
    assert.match(station, /^[a-z0-9-]+$/);
    assert.ok(allowedClasses.has(className), `${station} has unexpected class ${className}`);
  }

  // idle and unknown stations are absent from all policy sets
  assert.equal(IDENTITY_CRITICAL_AGENTS.has("idle"), false);
  assert.equal(IDENTITY_CRITICAL_AGENTS.has("unknown"), false);
  assert.equal(CREDENTIAL_AGENTS.has("idle"), false);
  assert.equal(CREDENTIAL_AGENTS.has("unknown"), false);
  assert.equal(STATION_CLASSES["idle"], undefined);
  assert.equal(STATION_CLASSES["unknown"], undefined);
});

// ---------------------------------------------------------------------------------------------
// 2. computeFingerprint: mirrors lib/findings.py
// ---------------------------------------------------------------------------------------------

test("computeFingerprint reproduces the factory's fingerprints for every verifiable real fixture", () => {
  let verifiedCount = 0;
  for (const name of readdirSync(FIXTURES).filter((n) => n.endsWith("-delta.md"))) {
    const agent = agentFromReportName(name);
    const report = parseFixture(name, agent);
    for (const finding of report.findings) {
      if (finding.identitySource === "unverifiable") {
        // Reduced/step-summary fixture (e.g. vuln-discovery) carries no snippet line
        continue;
      }
      assert.equal(
        finding.identitySource,
        "recomputed-and-verified",
        `${name}: recomputed fingerprint ${finding.fingerprint} does not match prefix ${finding.fingerprintFromReport}`,
      );
      assert.ok(
        finding.fingerprint.startsWith(finding.fingerprintFromReport),
        `${name}: ${finding.fingerprint} does not start with report prefix ${finding.fingerprintFromReport}`,
      );
      verifiedCount += 1;
    }
  }
  assert.ok(verifiedCount >= 5, `expected to verify >= 5 real fixture findings, verified ${verifiedCount}`);
});

test("computeFingerprint normalizes path separators, leading ./, and whitespace", () => {
  const a = computeFingerprint({
    agent: "qa-station",
    ruleId: "flake-test",
    path: "./tests\\unit\\sub\\test.ts",
    snippet: "  const  x   =  await  foo( ); \n\t ",
  });
  const b = computeFingerprint({
    agent: "qa-station",
    ruleId: "flake-test",
    path: "tests/unit/sub/test.ts",
    snippet: "const x = await foo( );",
  });
  assert.equal(a, b);
  assert.equal(normalizePath(".\\foo\\bar/baz.js"), "foo/bar/baz.js");
  assert.equal(normalizePath("///root/path"), "root/path");
  assert.equal(normalizePath(null), "");
  assert.equal(normalizeText("   multiple   \n\t spaces   here  "), "multiple spaces here");
  assert.equal(normalizeText(null), "");
});

test("tampered fingerprint prefix yields recomputed-mismatch and is skipped from publishing", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const tampered = { ...finding, fingerprintFromReport: "0".repeat(16), identitySource: "recomputed-mismatch" };
  const verdict = routeFinding(tampered);
  assert.equal(verdict.action, "skip");
  assert.match(verdict.reasons[0], /identity mismatch/);
});

// ---------------------------------------------------------------------------------------------
// 3. Severity mapping: fail-closed, identity before model label
// ---------------------------------------------------------------------------------------------

test("parseBadge parses single severity, routed elevation, and false positive", () => {
  assert.deepEqual(parseBadge("MEDIUM"), { reported: "medium" });
  assert.deepEqual(parseBadge("HIGH · routed critical"), { reported: "high", routed: "critical" });
  assert.deepEqual(parseBadge("FALSE POSITIVE"), { falsePositive: true });
});

test("severity is fail-closed: unrecognized or missing badge in fixture parses as critical", () => {
  const fixtureText = fixture("voicebox-qa-station-delta.md");
  for (const badge of ["SEVERE", "MEDUM", "5", "IMPORTANT", "UNKNOWN"]) {
    const rewritten = fixtureText.replace("[MEDIUM]", `[${badge}]`);
    assert.notEqual(rewritten, fixtureText, "badge replacement must occur");
    const [finding] = parseReport(rewritten, { agent: "qa-station" }).findings;
    assert.equal(finding.severityReported, badge.toLowerCase());
    assert.equal(
      finding.effectiveSeverity,
      "critical",
      `badge "${badge}" must fail closed to critical, got ${finding.effectiveSeverity}`,
    );
  }
});

test("an identity-critical station elevates a plain [MEDIUM] badge to critical without routed badge", () => {
  const rewritten = fixture("voicebox-secret-scan-delta.md").replace("[MEDIUM · routed critical]", "[MEDIUM]");
  assert.match(rewritten, /\[MEDIUM\]/);
  const [finding] = parseReport(rewritten, { agent: "secret-scan" }).findings;
  assert.equal(finding.severityReported, "medium");
  assert.equal(finding.severityRouted, null);
  assert.equal(finding.identityCritical, true);
  assert.equal(finding.effectiveSeverity, "critical", "secret-scan must be critical even on a plain MEDIUM label");
  const verdict = routeFinding(finding);
  assert.equal(verdict.action, "issue");
  assert.match(verdict.reasons[0], /identity-critical station `secret-scan`: routed critical/);
});

// ---------------------------------------------------------------------------------------------
// 4. Sanitisation: credential shapes masked, candidate withheld, published text clean
// ---------------------------------------------------------------------------------------------

test("every credential shape the factory masks is masked at runtime", () => {
  // Built at runtime — no realistic token is ever committed to repository
  const shapes = [
    ["pem-block", `-----BEGIN PRIVATE KEY-----\nMII${"A".repeat(64)}\n-----END PRIVATE KEY-----`],
    ["openai-key", `sk-${"B".repeat(24)}`],
    ["openai-key-proj", `sk-proj-${"C".repeat(24)}`],
    ["stripe-key", `sk_live_${"D".repeat(24)}`],
    ["google-api-key", `AIza${"E".repeat(35)}`],
    ["google-oauth", `ya29.${"F".repeat(25)}`],
    ["gitlab-pat", `glpat-${"G".repeat(20)}`],
    ["npm-token", `npm_${"H".repeat(36)}`],
    ["private-key", `-----BEGIN RSA PRIVATE KEY-----`],
    ["aws-access-key", `AKIA1234567890ABCDEF`],
    ["github-pat", `ghp_${"I".repeat(36)}`],
    ["github-pat-fine", `github_pat_${"J".repeat(22)}_${"K".repeat(59)}`],
    ["slack-token", `xoxb-12345678901-123456789012-${"L".repeat(24)}`],
    ["generic-api-key", `api_key = "${"M".repeat(32)}"`],
    ["jwt-token", `ey${"N".repeat(15)}.ey${"O".repeat(15)}.${"P".repeat(15)}`],
  ];

  for (const [name, token] of shapes) {
    const masked = maskText(`header ${token} footer`);
    assert.ok(!masked.includes(token), `${name} survived masking: ${masked}`);
    assert.match(masked, /\[redacted:[a-z-]+\]/);
  }
});

test("canary credential echoed into description or remediation is masked", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const canary = `sk-${"Z".repeat(24)}`;
  const withEcho = {
    ...finding,
    description: `model echoed raw token: ${canary} in analysis`,
    remediation: `rotate ${canary} immediately`,
  };
  const sanitized = sanitizeFinding(withEcho);
  assert.ok(!sanitized.description.includes(canary));
  assert.ok(sanitized.description.includes("[redacted:openai-key]"));
  assert.ok(!sanitized.remediation.includes(canary));
  assert.ok(sanitized.remediation.includes("[redacted:openai-key]"));
});

test("identity-critical station snippet is withheld wholesale for secret-scan and vuln-discovery", () => {
  const [secretFinding] = parseFixture("voicebox-secret-scan-delta.md", "secret-scan").findings;
  const secretSanitized = sanitizeFinding(secretFinding);
  assert.ok(secretSanitized.snippet.startsWith("[withheld: matched value not published"));
  assert.ok(!secretSanitized.snippet.includes("CANARY-fixture-not-a-real-credential"));

  const vulnFinding = {
    agent: "vuln-discovery",
    ruleId: "sqli-probe",
    path: "server/db.ts",
    lineNumber: "44",
    snippet: "' OR '1'='1' -- attack payload",
  };
  const vulnSanitized = sanitizeFinding(vulnFinding);
  assert.ok(vulnSanitized.snippet.startsWith("[withheld: matched value not published"));
  assert.ok(!vulnSanitized.snippet.includes("' OR '1'='1'"));
});

test("home paths and private root directory are elided from finding fields", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const rooted = {
    ...finding,
    description: "read from /home/operator/.voicebox/factory-reports/delta.md and /Users/developer/voicebox/x",
    remediation: "check /home/operator/.voicebox/factory-reports",
    path: "/home/operator/.voicebox/factory-reports/delta.md",
  };
  const sanitized = sanitizeFinding(rooted, { privateRoot: "/home/operator/.voicebox/factory-reports" });
  assert.ok(!sanitized.description.includes("/home/operator"));
  assert.ok(!sanitized.description.includes("/Users/developer"));
  assert.ok(sanitized.description.includes("<private-report-dir>"));
  assert.ok(sanitized.remediation.includes("<private-report-dir>"));
  assert.ok(sanitized.path.includes("<private-report-dir>"));
});

test("steering 1 (title elision): issue.title is built from sanitised title, eliding homedir and privateRoot", () => {
  const [qaFinding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const privateRoot = "/tmp/secret-private-reports";
  const userHome = homedir();
  const findingWithHomeInTitle = {
    ...qaFinding,
    title: `chip assertion at ${userHome}/voicebox and ${privateRoot}/report-delta.md`,
  };
  const verdict = routeFinding(findingWithHomeInTitle);
  const issue = buildIssue(findingWithHomeInTitle, verdict, { privateRoot, repo: "owner/voicebox" });

  assert.ok(
    !issue.title.includes(userHome),
    `issue.title leaked home directory: ${issue.title}`,
  );
  assert.ok(
    !issue.title.includes(privateRoot),
    `issue.title leaked privateRoot: ${issue.title}`,
  );
  assert.ok(issue.title.includes("~"), `issue.title should contain ~ replacement: ${issue.title}`);
  assert.ok(
    issue.title.includes("<private-report-dir>"),
    `issue.title should contain <private-report-dir>: ${issue.title}`,
  );
});

test("steering 2 (credential-rule withholding): non-credential station with credential rule id withholds values", () => {
  for (const hint of CREDENTIAL_RULE_HINTS) {
    const finding = { agent: "qa-station", ruleId: `test-${hint}-finding` };
    assert.equal(isCredentialFinding(finding), true, `ruleId containing "${hint}" must be a credential finding`);
  }

  // qa-station is not a credential station, but rule id contains "password"
  const passwordSecret = "MyVerySecretPassword_XYZ_987";
  const nonCredFinding = {
    agent: "qa-station",
    ruleId: "hardcoded-password",
    path: "src/auth/login.ts",
    lineNumber: "12",
    state: "new",
    title: `echoed ${passwordSecret} in title`,
    description: `model found ${passwordSecret} in db connection`,
    remediation: `rotate password ${passwordSecret}`,
    snippet: `const pwd = "${passwordSecret}";`,
    className: "quality",
    effectiveSeverity: "high",
    severityReported: "high",
    identityCritical: false,
    fingerprint: "1".repeat(64),
    identitySource: "recomputed-and-verified",
  };

  const verdict = routeFinding(nonCredFinding);
  const issue = buildIssue(nonCredFinding, verdict, { repo: "owner/voicebox" });

  // Assert secret string is present NOWHERE in published issue title or body
  assert.ok(!issue.title.includes(passwordSecret), "secret leaked into issue title");
  assert.ok(!issue.body.includes(passwordSecret), "secret leaked into issue body");
  assert.ok(issue.body.includes(WITHHELD_NOTE), "body must include WITHHELD_NOTE");
  assert.ok(issue.body.includes(GENERIC_REMEDIATION), "body must include GENERIC_REMEDIATION");
});

test("steering 3 (derived text for credential findings): secret-scan publishes ONLY derived facts, no triage model prose", () => {
  const secretValue = "MyDatabasePassword_999";
  const secretFinding = {
    agent: "secret-scan",
    ruleId: "generic-api-key",
    path: "config/database.env",
    lineNumber: "25",
    state: "new",
    title: `Triage notes with ${secretValue}`,
    description: `The triage model noted ${secretValue} in prose`,
    remediation: `Change ${secretValue} to environment variable`,
    snippet: `DB_PASSWORD="${secretValue}"`,
    className: "security",
    effectiveSeverity: "critical",
    severityReported: "critical",
    identityCritical: true,
    fingerprint: "2".repeat(64),
    identitySource: "recomputed-and-verified",
  };

  const verdict = routeFinding(secretFinding);
  const issue = buildIssue(secretFinding, verdict, { repo: "owner/voicebox" });

  // Non-pattern secret string must appear NOWHERE in title or body
  assert.ok(!issue.title.includes(secretValue), `secretValue found in issue.title: ${issue.title}`);
  assert.ok(!issue.body.includes(secretValue), `secretValue found in issue.body: ${issue.body}`);

  // Derived facts must appear
  assert.match(issue.title, /generic-api-key match at config\/database\.env:25/);
  assert.ok(issue.body.includes(GENERIC_REMEDIATION));
  assert.ok(issue.body.includes(WITHHELD_NOTE));
  assert.match(issue.body, /The deterministic scanner matched `generic-api-key` at `config\/database\.env:25`/);
});

// ---------------------------------------------------------------------------------------------
// 5. The publication declaration
// ---------------------------------------------------------------------------------------------

test("every built issue contains PUBLICATION_DECLARATION and required deliberate bypass statements", () => {
  const [qaFinding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const [perfFinding] = parseFixture("voicebox-perf-review-delta.md", "perf-review").findings;
  const [secretFinding] = parseFixture("voicebox-secret-scan-delta.md", "secret-scan").findings;

  for (const finding of [qaFinding, perfFinding, secretFinding]) {
    const verdict = routeFinding(finding);
    const issue = buildIssue(finding, verdict, { repo: "owner/voicebox" });

    assert.ok(issue.body.includes(PUBLICATION_DECLARATION), "missing PUBLICATION_DECLARATION in issue body");
    assert.match(
      issue.body,
      /bypasses the factory's\s+public sinks on purpose/,
      "issue body must state deliberate bypass of public sinks",
    );
    assert.match(
      issue.body,
      /embargo/,
      "issue body must reference the factory embargo",
    );
    assert.match(
      issue.body,
      /No bead was created from the scan/,
      "issue body must state no bead was created from the scan",
    );
  }
});

// ---------------------------------------------------------------------------------------------
// 6. Markers: round-trip and embedding
// ---------------------------------------------------------------------------------------------

test("markerFor and parseMarkers round-trip all marker fields including promotedTo", () => {
  const finding = {
    fingerprint: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    agent: "qa-station",
    effectiveSeverity: "medium",
    state: "new",
  };
  const markerText = markerFor(finding, { humanReview: true });
  const parsed = parseMarkers(markerText);
  assert.equal(parsed.fingerprint, finding.fingerprint);
  assert.equal(parsed.station, finding.agent);
  assert.equal(parsed.severity, finding.effectiveSeverity);
  assert.equal(parsed.state, finding.state);
  assert.equal(parsed.humanReview, true);
  assert.equal(parsed.promotedTo, null);

  const withPromoted = `${markerText}\n<!-- factory-promoted: voicebox-beads-h1u0 -->`;
  const parsedPromoted = parseMarkers(withPromoted);
  assert.equal(parsedPromoted.promotedTo, "voicebox-beads-h1u0");
});

test("buildIssue embeds parseable markers matching finding properties in the issue body", () => {
  const [finding] = parseFixture("voicebox-qa-station-delta.md", "qa-station").findings;
  const verdict = routeFinding(finding, { confirmedFunctionalityChange: true });
  const issue = buildIssue(finding, verdict, { repo: "owner/voicebox" });

  const markers = parseMarkers(issue.body);
  assert.equal(markers.fingerprint, finding.fingerprint);
  assert.equal(markers.station, finding.agent);
  assert.equal(markers.severity, finding.effectiveSeverity);
  assert.equal(markers.state, finding.state);
  assert.equal(markers.humanReview, true);
  assert.equal(markers.promotedTo, null);
});

// ---------------------------------------------------------------------------------------------
// 7. Seeded HIGH finding and embargo bypass
// ---------------------------------------------------------------------------------------------

test("file-issues publishes a HIGH finding from perf-review fixture with sanitized body", () => {
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-perf-review-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-perf-review-delta.md": fixture("voicebox-perf-review-delta.md") },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const createCall = res.ghCalls.find((call) => call.startsWith("issue create"));
    assert.ok(createCall, `expected issue create call in ghCalls: ${res.ghCalls.join("\n")}`);
    assert.match(createCall, /--title.*\[factory\/high\] perf-review: Startup probe blocks the boot banner/);
    assert.match(createCall, /--body.*blocking-boot-probe/);
    assert.match(createCall, /--body.*Do not await the probe before printing the banner/);
    assert.match(createCall, /--label.*enhancement/);
    assert.match(res.stdout, /published: [0-9a-f]{16} -> https:\/\/github\.com\/owner\/voicebox\/issues\/100/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("embargo bypass made safe: secret-scan finding is published as critical issue with candidate withheld", () => {
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-secret-scan-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-secret-scan-delta.md": fixture("voicebox-secret-scan-delta.md") },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const createCall = res.ghCalls.find((call) => call.startsWith("issue create"));
    assert.ok(createCall, `expected issue create call in ghCalls: ${res.ghCalls.join("\n")}`);
    assert.match(createCall, /--title.*\[factory\/critical\] secret-scan: generic-api-key match at config\/example\.env:12/);
    assert.match(createCall, /--body.*Raw candidate withheld/);
    assert.ok(!createCall.includes("CANARY-fixture-not-a-real-credential"), "raw candidate leaked into issue create");
    assert.match(createCall, /identity-critical station `secret-scan`: routed critical and published deliberately/);
    assert.match(res.stdout, /published: [0-9a-f]{16} -> https:\/\/github\.com\/owner\/voicebox\/issues\/100/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------------------------
// 8. Dedupe on publish
// ---------------------------------------------------------------------------------------------

test("file-issues skips creating issue when open issue already tracks the fingerprint", () => {
  const fp = computeFingerprint({
    agent: "qa-station",
    ruleId: "flake-instrumentation",
    path: "tests/room-folders.test.mjs",
    snippet: 'await page.waitForSelector("text=Projects")',
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        list) echo '[{"number": 42, "state": "OPEN", "body": "<!-- factory-fingerprint: ${fp} -->"}]' ;;
        create) echo "SHOULD_NOT_BE_CALLED" >&2; exit 1 ;;
        *) exit 1 ;;
      esac
      ;;
    label) echo '[]' ;;
  esac`;
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    stubGh,
  });
  try {
    assert.equal(res.status, 2, `expected exit code 2 when all duplicate: ${res.stdout}\n${res.stderr}`);
    assert.equal(res.ghCalls.some((c) => c.startsWith("issue create")), false, "duplicate issue was created");
    assert.match(res.stdout, /duplicate: [0-9a-f]{16} \(an open issue already tracks it: #42\) — skipped/);
    assert.match(res.stdout, /issues: 0 published, 1 duplicate/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("file-issues skips creating issue when closed issue tracks fingerprint and state is new", () => {
  const fp = computeFingerprint({
    agent: "qa-station",
    ruleId: "flake-instrumentation",
    path: "tests/room-folders.test.mjs",
    snippet: 'await page.waitForSelector("text=Projects")',
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        list) echo '[{"number": 55, "state": "CLOSED", "body": "<!-- factory-fingerprint: ${fp} -->"}]' ;;
        create) echo "SHOULD_NOT_BE_CALLED" >&2; exit 1 ;;
        *) exit 1 ;;
      esac
      ;;
    label) echo '[]' ;;
  esac`;
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    stubGh,
  });
  try {
    assert.equal(res.status, 2, `expected exit code 2: ${res.stdout}\n${res.stderr}`);
    assert.equal(res.ghCalls.some((c) => c.startsWith("issue create")), false, "duplicate issue was created");
    assert.match(res.stdout, /duplicate: [0-9a-f]{16} \(a closed issue already tracked it and nothing regressed: #55\) — skipped/);
    assert.match(res.stdout, /issues: 0 published, 1 duplicate/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("file-issues republishes when closed issue tracks fingerprint but finding has regressed", () => {
  const fp = computeFingerprint({
    agent: "qa-station",
    ruleId: "flake-instrumentation",
    path: "tests/room-folders.test.mjs",
    snippet: 'await page.waitForSelector("text=Projects")',
  });
  const regressedReport = fixture("voicebox-qa-station-delta.md").replace("(`new`)", "(`regressed`)");
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        list) echo '[{"number": 55, "state": "CLOSED", "body": "<!-- factory-fingerprint: ${fp} -->"}]' ;;
        create) echo "https://github.com/owner/voicebox/issues/77" ;;
        *) exit 1 ;;
      esac
      ;;
    label) echo '[{"name":"bug"}]' ;;
  esac`;
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": regressedReport },
    stubGh,
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    assert.ok(res.ghCalls.some((c) => c.startsWith("issue create")), "expected regressed finding to be published");
    assert.match(res.stdout, /published: [0-9a-f]{16} -> https:\/\/github\.com\/owner\/voicebox\/issues\/77/);
    assert.match(res.stdout, /issues: 1 published, 0 duplicate/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("file-issues publishes nothing and exits 1 when gh issue list fails", () => {
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        list) echo "API rate limit exceeded" >&2; exit 1 ;;
        create) echo "SHOULD_NOT_BE_CALLED" >&2; exit 1 ;;
      esac
      ;;
  esac`;
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    stubGh,
  });
  try {
    assert.equal(res.status, 1, `expected status 1: ${res.stdout}\n${res.stderr}`);
    assert.match(res.stderr, /could not list existing issues in owner\/voicebox: nothing published/);
    assert.equal(res.ghCalls.some((c) => c.startsWith("issue create")), false);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("isIssueDuplicate unit logic distinguishes open, closed-new, and closed-regressed", () => {
  const fp = "a".repeat(64);
  const openMap = new Map([[fp, [{ number: "12", state: "OPEN" }]]]);
  assert.equal(isIssueDuplicate({ fingerprint: fp, state: "new" }, openMap).numbers[0], "12");
  assert.equal(isIssueDuplicate({ fingerprint: fp, state: "regressed" }, openMap).why, "an open issue already tracks it");

  const closedMap = new Map([[fp, [{ number: "18", state: "CLOSED" }]]]);
  assert.equal(isIssueDuplicate({ fingerprint: fp, state: "new" }, closedMap).numbers[0], "18");
  assert.equal(isIssueDuplicate({ fingerprint: fp, state: "regressed" }, closedMap), null);

  const emptyMap = new Map();
  assert.equal(isIssueDuplicate({ fingerprint: fp, state: "new" }, emptyMap), null);
});

// ---------------------------------------------------------------------------------------------
// 9. NO BEAD FROM A SCAN: scans write no beads and touch no repository files
// ---------------------------------------------------------------------------------------------

test("no bead from a scan: plan mode never calls bd and writes nothing to repo", () => {
  const res = runCli({
    args: ["--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    assert.equal(res.bdCalls.length, 0, `plan mode called bd: ${res.bdCalls.join(" | ")}`);
    assert.deepEqual(readdirSync(res.repo), [], "plan mode wrote files into target repo");
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("no bead from a scan: file-issues mode never calls bd and writes nothing to repo", () => {
  const res = runCli({
    args: ["--file-issues", "--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    assert.equal(res.bdCalls.length, 0, `file-issues called bd: ${res.bdCalls.join(" | ")}`);
    assert.deepEqual(readdirSync(res.repo), [], "file-issues wrote files into target repo");
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("no bead from a scan: script contains no automatic bead creation in scan paths", () => {
  const source = readFileSync(SCRIPT, "utf8");
  const bdCreateMatches = [...source.matchAll(/spawnSync\(\s*["']bd["'],\s*\[\s*["']create["']/g)];
  assert.equal(bdCreateMatches.length, 1, "bd create should only be called in one place in the script (promote)");
  const promoteIndex = source.indexOf("function promote(");
  assert.ok(promoteIndex > 0, "function promote exists");
  assert.ok(bdCreateMatches[0].index > promoteIndex, "bd create is inside promote");
  const mainIndex = source.indexOf("function main(");
  assert.ok(bdCreateMatches[0].index < mainIndex, "bd create is before main");
});

// ---------------------------------------------------------------------------------------------
// 10. --promote: explicit reviewed conversion of an issue to a bead
// ---------------------------------------------------------------------------------------------

test("promote: refuses when issue body carries no factory fingerprint marker", () => {
  const issueJson = JSON.stringify({
    number: 10,
    state: "OPEN",
    title: "some issue",
    body: "regular issue without markers",
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueJson}
EOF
        ;;
      esac
      ;;
  esac`;
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--repo", "owner/voicebox"],
    stubGh,
  });
  try {
    assert.equal(res.status, 1);
    assert.match(res.stderr, /carries no factory fingerprint marker: refusing to promote/);
    assert.equal(res.bdCalls.length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

/** A `gh` stub whose `issue view` prints `issueJson` (the file's existing stub style). */
const ghStubViewing = (issueJson) => `case "$1" in
  issue)
    case "$2" in
      view) cat << 'EOF'
${issueJson}
EOF
        ;;
      comment) echo "https://github.com/owner/voicebox/issues/10#issuecomment-2" ;;
      list) echo '[]' ;;
      *) echo "unknown issue subcmd: $2" >&2; exit 1 ;;
    esac
    ;;
  label) echo '[{"name":"bug"},{"name":"enhancement"},{"name":"documentation"},{"name":"human-review"}]' ;;
  *) echo "unknown gh cmd: $1" >&2; exit 1 ;;
esac`;

test("promote: refuses an issue that carries no review record", () => {
  // The review has to be ON the issue: a name typed at promotion time proves nothing.
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--repo", "owner/voicebox"],
    stubGh: ghStubViewing(JSON.stringify({
      number: 10,
      state: "OPEN",
      title: "[factory/medium] qa-station: stub",
      body: "<!-- factory-fingerprint: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef -->\n<!-- factory-station: qa-station -->\n<!-- factory-severity: medium -->\n<!-- factory-state: new -->\n**Rule**: `flake-instrumentation`",
      comments: [],
    })),
  });
  try {
    assert.equal(res.status, 1);
    assert.match(res.stderr, /carries no review record/);
    assert.equal(res.bdCalls.length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promote: refuses when --reviewed-by contradicts the review recorded on the issue", () => {
  const fp = "c".repeat(64);
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "bob", "--repo", "owner/voicebox"],
    stubGh: ghStubViewing(
      JSON.stringify({
        number: 10,
        state: "OPEN",
        title: "[factory/medium] qa-station: stub",
        body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: qa-station -->\n<!-- factory-severity: medium -->\n<!-- factory-state: new -->`,
        comments: [{ body: "<!-- factory-review: alice -->" }],
      }),
    ),
  });
  try {
    assert.equal(res.status, 1);
    assert.match(res.stderr, /does not match the reviewer recorded on owner\/voicebox#10 \(alice\)/);
    assert.equal(res.bdCalls.length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("--review records the verdict on the issue (and is what promotion reads)", () => {
  const res = runCli({
    args: ["--review", "10", "--reviewed-by", "alice", "--notes", "looks right", "--repo", "owner/voicebox"],
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const comment = res.ghCalls.find((call) => /^issue comment 10/.test(call));
    assert.ok(comment, `no review comment posted: ${res.ghCalls.join(" | ")}`);
    assert.match(comment, /<!-- factory-review: alice -->/);
    assert.match(comment, /looks right/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promote: refuses a self-test issue and a closed issue", () => {
  const fp = "a".repeat(64);
  const selfTest = runCli({
    args: ["--promote", "10", "--repo", "owner/voicebox"],
    stubGh: ghStubViewing(JSON.stringify({
      number: 10, state: "OPEN", title: "t",
      body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: perf-review -->\n<!-- factory-severity: high -->\n<!-- factory-state: new -->\n<!-- factory-self-test -->`,
      comments: [{ body: "<!-- factory-review: alice -->" }],
    })),
  });
  try {
    assert.equal(selfTest.status, 1);
    assert.match(selfTest.stderr, /marked as a publisher self-test/);
    assert.equal(selfTest.bdCalls.length, 0);
  } finally {
    rmSync(selfTest.box, { recursive: true, force: true });
  }
  const closed = runCli({
    args: ["--promote", "10", "--repo", "owner/voicebox"],
    stubGh: ghStubViewing(JSON.stringify({
      number: 10, state: "CLOSED", title: "t",
      body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: perf-review -->\n<!-- factory-severity: high -->\n<!-- factory-state: new -->`,
      comments: [{ body: "<!-- factory-review: alice -->" }],
    })),
  });
  try {
    assert.equal(closed.status, 1);
    assert.match(closed.stderr, /is closed: a closed issue is not work to start/);
    assert.equal(closed.bdCalls.length, 0);
  } finally {
    rmSync(closed.box, { recursive: true, force: true });
  }
});

test("promote: refuses when issue was already promoted (promoted-to marker in body or comment)", () => {
  const fp = "a".repeat(64);
  const issueWithBodyMarker = JSON.stringify({
    number: 10,
    state: "OPEN",
    title: "issue",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-promoted: voicebox-beads-prev -->`,
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGhBody = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueWithBodyMarker}
EOF
        ;;
      esac
      ;;
  esac`;
  const resBody = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--repo", "owner/voicebox"],
    stubGh: stubGhBody,
  });
  try {
    assert.equal(resBody.status, 1);
    assert.match(resBody.stderr, /was already promoted to voicebox-beads-prev: refusing to create a second bead/);
    assert.equal(resBody.bdCalls.length, 0);
  } finally {
    rmSync(resBody.box, { recursive: true, force: true });
  }

  // Also test promoted-to marker present in comments
  const issueWithCommentMarker = JSON.stringify({
    number: 11,
    state: "OPEN",
    title: "issue 11",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: qa-station -->`,
    comments: [{ body: "<!-- factory-promoted: voicebox-beads-comment-prev -->" }],
  });
  const stubGhComment = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueWithCommentMarker}
EOF
        ;;
      esac
      ;;
  esac`;
  const resComment = runCli({
    args: ["--promote", "11", "--reviewed-by", "alice", "--repo", "owner/voicebox"],
    stubGh: stubGhComment,
  });
  try {
    assert.equal(resComment.status, 1);
    assert.match(resComment.stderr, /was already promoted to voicebox-beads-comment-prev: refusing to create a second bead/);
    assert.equal(resComment.bdCalls.length, 0);
  } finally {
    rmSync(resComment.box, { recursive: true, force: true });
  }
});

test("promote: refuses when bead with that fingerprint already exists in bd list", () => {
  const fp = "b".repeat(64);
  const issueJson = JSON.stringify({
    number: 10,
    state: "OPEN",
    title: "issue",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: qa-station -->`,
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueJson}
EOF
        ;;
      esac
      ;;
  esac`;
  const stubBd = `case "$1" in
    list) echo '[{"id": "voicebox-beads-existing", "status": "open", "external_ref": "factory:${fp}"}]' ;;
  esac`;
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--repo", "owner/voicebox"],
    stubGh,
    stubBd,
  });
  try {
    assert.equal(res.status, 1);
    assert.match(res.stderr, /is already tracked by voicebox-beads-existing: nothing filed/);
    assert.equal(res.bdCalls.filter((c) => c.startsWith("create")).length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promote: dry-run prints bead plan without calling bd create", () => {
  const fp = "c".repeat(64);
  const issueJson = JSON.stringify({
    number: 10,
    state: "OPEN",
    title: "issue title",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: qa-station -->\n<!-- factory-severity: medium -->\n**Rule**: \`flake-instrumentation\``,
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueJson}
EOF
        ;;
      esac
      ;;
  esac`;
  const stubBd = `case "$1" in
    list) echo '[]' ;;
    create) echo "SHOULD_NOT_BE_CALLED" >&2; exit 1 ;;
  esac`;
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--repo", "owner/voicebox"],
    stubGh,
    stubBd,
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    assert.match(res.stdout, /would file task P2: \[qa-station\] issue title/);
    assert.match(res.stdout, new RegExp(`external-ref factory:${fp}`));
    assert.equal(res.bdCalls.filter((c) => c.startsWith("create")).length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promote: with --apply creates bead with external-ref and comments back on issue", () => {
  const fp = "d".repeat(64);
  const issueJson = JSON.stringify({
    number: 10,
    state: "OPEN",
    title: "issue title",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: qa-station -->\n<!-- factory-severity: medium -->\n**Rule**: \`flake-instrumentation\``,
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueJson}
EOF
        ;;
        comment) echo "https://github.com/owner/voicebox/issues/10#issuecomment-123" ;;
      esac
      ;;
  esac`;
  const stubBd = `case "$1" in
    list) echo '[]' ;;
    create) echo "voicebox-beads-h1u0" ;;
  esac`;
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--apply", "--repo", "owner/voicebox"],
    stubGh,
    stubBd,
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const bdCreate = res.bdCalls.find((c) => c.startsWith("create"));
    assert.ok(bdCreate, `expected bd create: ${res.bdCalls.join("\n")}`);
    assert.match(bdCreate, new RegExp(`--external-ref factory:${fp}`));
    assert.match(bdCreate, /--priority 2/);
    assert.match(bdCreate, /--labels factory/);
    assert.match(bdCreate, /--type task/);
    const ghComment = res.ghCalls.find((c) => c.startsWith("issue comment 10"));
    assert.ok(ghComment, `expected gh issue comment: ${res.ghCalls.join("\n")}`);
    assert.match(ghComment, /Promoted to bead `voicebox-beads-h1u0` by alice/);
    assert.match(ghComment, /<!-- factory-promoted: voicebox-beads-h1u0 -->/);
    assert.match(res.stdout, new RegExp(`filed: ${fp.slice(0, 16)} -> voicebox-beads-h1u0`));
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promote: high severity finding gets priority 1 on promotion", () => {
  const fp = "f".repeat(64);
  const issueJson = JSON.stringify({
    number: 20,
    state: "OPEN",
    title: "high perf issue",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: perf-review -->\n<!-- factory-severity: high -->\n**Rule**: \`blocking-boot-probe\``,
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueJson}
EOF
        ;;
        comment) echo "ok" ;;
      esac
      ;;
  esac`;
  const stubBd = `case "$1" in
    list) echo '[]' ;;
    create) echo "voicebox-beads-p1" ;;
  esac`;
  const res = runCli({
    args: ["--promote", "20", "--reviewed-by", "alice", "--apply", "--repo", "owner/voicebox"],
    stubGh,
    stubBd,
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const bdCreate = res.bdCalls.find((c) => c.startsWith("create"));
    assert.ok(bdCreate);
    assert.match(bdCreate, /--priority 1/, `high severity issue must be promoted at priority 1: ${bdCreate}`);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promote: with --apply on functionality-changing finding creates BLOCKED bead and records decision comment", () => {
  const fp = "e".repeat(64);
  const issueJson = JSON.stringify({
    number: 15,
    state: "OPEN",
    title: "[human-review] issue title",
    body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: qa-station -->\n<!-- factory-severity: medium -->\n<!-- factory-human-review -->\n**Rule**: \`flake-instrumentation\``,
    comments: [{ body: "<!-- factory-review: alice -->" }],
  });
  const stubGh = `case "$1" in
    issue)
      case "$2" in
        view) cat << 'EOF'
${issueJson}
EOF
        ;;
        comment) echo "https://github.com/owner/voicebox/issues/15#issuecomment-456" ;;
      esac
      ;;
  esac`;
  const stubBd = `case "$1" in
    list) echo '[]' ;;
    create) echo "voicebox-beads-blk1" ;;
    update) echo "updated" ;;
    comment) echo "commented" ;;
  esac`;
  const res = runCli({
    args: ["--promote", "15", "--reviewed-by", "alice", "--apply", "--repo", "owner/voicebox"],
    stubGh,
    stubBd,
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const bdCreate = res.bdCalls.find((c) => c.startsWith("create"));
    assert.ok(bdCreate);
    assert.match(bdCreate, /--labels factory,human-review/);
    const bdUpdate = res.bdCalls.find((c) => c.startsWith("update voicebox-beads-blk1"));
    assert.ok(bdUpdate, `expected bd update: ${res.bdCalls.join("\n")}`);
    assert.match(bdUpdate, /--status blocked/);
    const bdComment = res.bdCalls.find((c) => c.startsWith("comment voicebox-beads-blk1"));
    assert.ok(bdComment, `expected bd comment: ${res.bdCalls.join("\n")}`);
    assert.match(bdComment, /Blocked pending human review/);
    const ghComment = res.ghCalls.find((c) => c.startsWith("issue comment 15"));
    assert.ok(ghComment);
    assert.match(ghComment, /The bead is BLOCKED pending the human review decision/);
    assert.match(ghComment, /<!-- factory-promoted: voicebox-beads-blk1 -->/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("beadForPromotion unit computes bead fields, types, and priorities for each severity", () => {
  const baseFinding = {
    station: "qa-station",
    ruleId: "flake-instrumentation",
    fingerprint: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    humanReview: false,
    severity: "medium",
    effectiveSeverity: "medium",
  };
  const issue = {
    url: "https://github.com/owner/voicebox/issues/10",
    title: "[factory/medium] qa-station: Flake chip",
  };
  const beadMedium = beadForPromotion({
    finding: baseFinding,
    issue,
    reviewedBy: "alice",
    repo: "owner/voicebox",
    issueNumber: 10,
  });
  assert.equal(beadMedium.priority, 2);
  assert.equal(beadMedium.type, "task");
  assert.equal(beadMedium.blocked, false);
  assert.equal(beadMedium.externalRef, "factory:" + baseFinding.fingerprint);
  assert.deepEqual(beadMedium.labels, ["factory"]);
  assert.match(beadMedium.description, /Promoted from the published factory issue \(owner\/voicebox#10\) by alice/);

  // High / critical priority 1
  const beadHigh = beadForPromotion({
    finding: { ...baseFinding, severity: "high", effectiveSeverity: "high" },
    issue,
    reviewedBy: "alice",
    repo: "owner/voicebox",
    issueNumber: 10,
  });
  assert.equal(beadHigh.priority, 1);

  const beadCritical = beadForPromotion({
    finding: { ...baseFinding, severity: "critical", effectiveSeverity: "critical", station: "secret-scan" },
    issue,
    reviewedBy: "alice",
    repo: "owner/voicebox",
    issueNumber: 10,
  });
  assert.equal(beadCritical.priority, 1);
  assert.equal(beadCritical.type, "bug", "secret-scan should map to type bug");

  // Low priority 3
  const beadLow = beadForPromotion({
    finding: { ...baseFinding, severity: "low", effectiveSeverity: "low" },
    issue,
    reviewedBy: "alice",
    repo: "owner/voicebox",
    issueNumber: 10,
  });
  assert.equal(beadLow.priority, 3);

  // Human review -> blocked: true, label human-review
  const beadBlocked = beadForPromotion({
    finding: { ...baseFinding, humanReview: true },
    issue: { ...issue, title: "[human-review] [factory/medium] qa-station: Flake chip" },
    reviewedBy: "alice",
    repo: "owner/voicebox",
    issueNumber: 10,
  });
  assert.equal(beadBlocked.blocked, true);
  assert.deepEqual(beadBlocked.labels, ["factory", "human-review"]);
  assert.match(beadBlocked.description, /The bead is BLOCKED until that decision is recorded/);
  assert.ok(!beadBlocked.title.includes("[human-review]"));
});

// ---------------------------------------------------------------------------------------------
// 11. Private-path refusal
// ---------------------------------------------------------------------------------------------

test("a report inside the repository is refused with exit 1 and nothing published", () => {
  const res = runCli({
    args: ["--report", join(FIXTURES, "voicebox-qa-station-delta.md"), "--repo", "owner/voicebox"],
    cwd: ROOT,
  });
  try {
    assert.equal(res.status, 1, res.stderr);
    assert.match(res.stderr, /inside the repository/);
    assert.equal(res.ghCalls.length, 0);
    assert.equal(res.bdCalls.length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("a report path escaping through symlink into repository is refused (realpath check)", () => {
  const box = mkdtempSync(join(tmpdir(), "factory-symlink-"));
  try {
    const link = join(box, "escape-delta.md");
    execFileSync("ln", ["-s", join(FIXTURES, "voicebox-qa-station-delta.md"), link]);
    assert.equal(isInside(link, ROOT), true);
    const res = runCli({
      args: ["--report", link, "--repo", "owner/voicebox"],
      cwd: ROOT,
    });
    assert.equal(res.status, 1, res.stderr);
    assert.match(res.stderr, /inside the repository/);
    assert.equal(res.ghCalls.length, 0);
  } finally {
    rmSync(box, { recursive: true, force: true });
  }
});

test("steering 4 (lexical symlink refusal): symlink inside repository pointing outside is refused", () => {
  const box = mkdtempSync(join(tmpdir(), "factory-lexical-symlink-"));
  const outsideReport = join(box, "voicebox-qa-station-delta.md");
  writeFileSync(outsideReport, fixture("voicebox-qa-station-delta.md"));

  // Create symlink inside ROOT pointing outside
  const linkPath = join(ROOT, "tests", "temp-lexical-test-delta.md");
  try {
    execFileSync("ln", ["-s", outsideReport, linkPath]);
    assert.equal(isInside(linkPath, ROOT), true, "symlink living inside repository pointing out must be refused");

    const res = runCli({
      args: ["--report", linkPath, "--repo", "owner/voicebox"],
      cwd: ROOT,
    });
    assert.equal(res.status, 1, res.stderr);
    assert.match(res.stderr, /inside the repository/);
    assert.equal(res.ghCalls.length, 0);
  } finally {
    if (existsSync(linkPath)) rmSync(linkPath, { force: true });
    rmSync(box, { recursive: true, force: true });
  }
});

test("the default private root is outside the repository and honours the env override", () => {
  const root = privateRootFromEnv({});
  assert.equal(isInside(join(root, "voicebox-qa-station-delta.md"), ROOT), false);
  assert.equal(privateRootFromEnv({ VOICEBOX_FACTORY_PRIVATE_DIR: "/tmp/explicit" }), resolve("/tmp/explicit"));
});

// ---------------------------------------------------------------------------------------------
// 12. Station resolution
// ---------------------------------------------------------------------------------------------

test("agentFromReportName derives station via longest known suffix, never greedy hyphen split", () => {
  assert.equal(agentFromReportName("voicebox-docs-drift-delta.md"), "docs-drift");
  assert.equal(agentFromReportName("voicebox-vuln-discovery-delta.md"), "vuln-discovery");
  assert.equal(agentFromReportName("voicebox-deps-supply-chain-delta.md"), "deps-supply-chain");
  assert.equal(agentFromReportName("voicebox-threat-model-delta.md"), "threat-model");
  assert.equal(agentFromReportName("voicebox-qa-station-delta.md"), "qa-station");
  assert.equal(agentFromReportName("reports/docs-drift-delta.md"), "docs-drift");
  assert.equal(agentFromReportName("voicebox-delta.md"), null);
  assert.equal(agentFromReportName("random.md"), null);
});

test("unknown station is refused with exit 1 unless --agent overrides it", () => {
  const unknown = runCli({
    args: ["--report", "voicebox-not-a-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-not-a-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  try {
    assert.equal(unknown.status, 1);
    assert.match(unknown.stderr, /cannot determine the station; pass --agent/);
  } finally {
    rmSync(unknown.box, { recursive: true, force: true });
  }

  const invalidOverride = runCli({
    args: ["--agent", "not-a-real-station", "--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  try {
    assert.equal(invalidOverride.status, 1);
    assert.match(invalidOverride.stderr, /unknown station "not-a-real-station"/);
  } finally {
    rmSync(invalidOverride.box, { recursive: true, force: true });
  }

  const validOverride = runCli({
    args: ["--agent", "qa-station", "--report", "voicebox-custom-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-custom-delta.md": fixture("voicebox-qa-station-delta.md") },
  });
  try {
    assert.equal(validOverride.status, 0, validOverride.stderr);
  } finally {
    rmSync(validOverride.box, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------------------------
// 13. Bands: low/info skipped by default; reduced form is unverifiable
// ---------------------------------------------------------------------------------------------

test("low and info findings are skipped by default and published with --include-low", () => {
  const [lowFinding] = parseFixture("voicebox-modern-web-delta.md", "modern-web").findings;
  assert.equal(lowFinding.effectiveSeverity, "low");
  assert.equal(routeFinding(lowFinding).action, "skip");
  assert.match(routeFinding(lowFinding).reasons[0], /low is below the published band/);
  assert.equal(routeFinding(lowFinding, { includeLow: true }).action, "issue");

  const infoFinding = { ...lowFinding, effectiveSeverity: "info" };
  assert.equal(routeFinding(infoFinding).action, "skip");
  assert.equal(routeFinding(infoFinding, { includeLow: true }).action, "issue");

  const skipRun = runCli({
    args: ["--report", "voicebox-modern-web-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-modern-web-delta.md": fixture("voicebox-modern-web-delta.md") },
  });
  try {
    assert.equal(skipRun.status, 2, "nothing actionable without --include-low");
    assert.match(skipRun.stdout, /NOT PUBLISHED/);
  } finally {
    rmSync(skipRun.box, { recursive: true, force: true });
  }

  const includeRun = runCli({
    args: ["--report", "voicebox-modern-web-delta.md", "--include-low", "--repo", "owner/voicebox"],
    reports: { "voicebox-modern-web-delta.md": fixture("voicebox-modern-web-delta.md") },
  });
  try {
    assert.equal(includeRun.status, 0, includeRun.stderr);
    assert.match(includeRun.stdout, /PUBLISH ISSUE.*P3 low modern-web/);
  } finally {
    rmSync(includeRun.box, { recursive: true, force: true });
  }
});

test("reduced-form finding without snippet has unverifiable identity and is not published", () => {
  const [reducedFinding] = parseFixture("voicebox-vuln-discovery-delta.md", "vuln-discovery").findings;
  assert.equal(reducedFinding.identitySource, "unverifiable");
  assert.equal(reducedFinding.fingerprint, null);
  assert.equal(reducedFinding.ruleId, "path-traversal", "rule id parsed from heading in reduced form");
  assert.equal(reducedFinding.effectiveSeverity, "critical", "vuln-discovery is identity-critical");
  const verdict = routeFinding(reducedFinding);
  assert.equal(verdict.action, "skip");
  assert.match(verdict.reasons[0], /identity unverifiable: the report carried no recomputable fingerprint/);

  const res = runCli({
    args: ["--report", "voicebox-vuln-discovery-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-vuln-discovery-delta.md": fixture("voicebox-vuln-discovery-delta.md") },
  });
  try {
    assert.equal(res.status, 2, "unverifiable finding should yield nothing actionable");
    assert.match(res.stdout, /NOT PUBLISHED.*vuln-discovery path-traversal/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------------------------
// 14. buildPlan over ALL fixtures at once
// ---------------------------------------------------------------------------------------------

test("buildPlan over ALL fixtures at once yields expected per-finding action map", () => {
  const names = readdirSync(FIXTURES).filter((n) => n.endsWith("-delta.md"));
  const files = names.map((n) => join(FIXTURES, n));
  const plan = buildPlan(files, {
    privateRoot: "/private",
    includeLow: false,
    functionality: new Set(),
    repo: "owner/voicebox",
  });

  const byAgentRule = Object.fromEntries(
    plan.map((entry) => [`${entry.finding.agent}:${entry.finding.ruleId}`, entry.verdict.action]),
  );

  assert.equal(byAgentRule["qa-station:flake-instrumentation"], "issue");
  assert.equal(byAgentRule["secret-scan:generic-api-key"], "issue", "embargo bypass: secret-scan finding is published as issue");
  assert.equal(byAgentRule["perf-review:blocking-boot-probe"], "issue");
  assert.equal(byAgentRule["docs-drift:stale-route-table"], "issue");
  assert.equal(byAgentRule["modern-web:legacy-light-dismiss"], "skip", "low severity skipped by default");
  assert.equal(byAgentRule["vuln-discovery:path-traversal"], "skip", "unverifiable identity skipped");

  // With includeLow: true
  const planWithLow = buildPlan(files, {
    privateRoot: "/private",
    includeLow: true,
    functionality: new Set(),
    repo: "owner/voicebox",
  });
  const byAgentRuleLow = Object.fromEntries(
    planWithLow.map((entry) => [`${entry.finding.agent}:${entry.finding.ruleId}`, entry.verdict.action]),
  );
  assert.equal(byAgentRuleLow["modern-web:legacy-light-dismiss"], "issue");

  // With functionality change confirmed
  const planWithFunc = buildPlan(files, {
    privateRoot: "/private",
    includeLow: false,
    functionality: new Set(["flake-instrumentation"]),
    repo: "owner/voicebox",
  });
  const qaEntry = planWithFunc.find((e) => e.finding.agent === "qa-station");
  assert.equal(qaEntry.verdict.action, "issue");
  assert.equal(qaEntry.verdict.humanReview, true);
  assert.match(qaEntry.issue.title, /^\[human-review\]/);
});

// ---------------------------------------------------------------------------------------------
// Auxiliary exports and edge cases
// ---------------------------------------------------------------------------------------------

test("resolveReportPath resolves absolute paths, cwd-relative files, or defaults to privateRoot", () => {
  const privateRoot = "/tmp/private-reports";
  assert.equal(resolveReportPath("/absolute/path/report.md", privateRoot), "/absolute/path/report.md");
  assert.equal(resolveReportPath("nonexistent-file.md", privateRoot), join(privateRoot, "nonexistent-file.md"));
});

test("chooseLabels maps finding station classes to repository labels and filters by knownLabels", () => {
  const securityFinding = { className: "security", agent: "secret-scan" };
  const docsFinding = { className: "docs", agent: "docs-drift" };
  const a11yFinding = { className: "ux", agent: "accessibility" };
  const perfFinding = { className: "perf", agent: "perf-review" };
  const verdictNormal = { humanReview: false };
  const verdictReview = { humanReview: true };

  assert.deepEqual(chooseLabels(securityFinding, verdictNormal), ["bug"]);
  assert.deepEqual(chooseLabels(docsFinding, verdictNormal), ["documentation"]);
  assert.deepEqual(chooseLabels(a11yFinding, verdictNormal), ["accessibility", "enhancement"]);
  assert.deepEqual(chooseLabels(perfFinding, verdictNormal), ["enhancement"]);
  assert.deepEqual(chooseLabels(perfFinding, verdictReview), ["enhancement", "human-review"]);

  assert.deepEqual(chooseLabels(perfFinding, verdictReview, ["enhancement"]), ["enhancement"]);
  assert.deepEqual(chooseLabels(perfFinding, verdictReview, ["other"]), []);
});

test("board I/O helpers parse tool outputs and fail safely on errors", () => {
  const fp = "1".repeat(64);

  // existingIssues
  const issuesMock = {
    status: 0,
    stdout: JSON.stringify([{ number: 1, state: "open", body: `<!-- factory-fingerprint: ${fp} -->` }]),
  };
  const issueMap = existingIssues("owner/repo", { run: () => issuesMock });
  assert.ok(issueMap.has(fp));
  assert.deepEqual(issueMap.get(fp), [{ number: "1", state: "open" }]);

  // existingIssues failure cases
  assert.equal(existingIssues("owner/repo", { run: () => ({ status: 1, error: new Error("fail") }) }), null);
  assert.equal(existingIssues("owner/repo", { run: () => ({ status: 0, stdout: "invalid-json" }) }), null);

  // knownLabels
  const labelsMock = { status: 0, stdout: JSON.stringify([{ name: "bug" }, { name: "enhancement" }]) };
  assert.deepEqual(knownLabels("owner/repo", { run: () => labelsMock }), ["bug", "enhancement"]);
  assert.equal(knownLabels("owner/repo", { run: () => ({ status: 1 }) }), null);

  // readIssue
  const issueViewMock = { status: 0, stdout: JSON.stringify({ number: 42, title: "issue 42" }) };
  assert.deepEqual(readIssue(42, "owner/repo", { run: () => issueViewMock }), { number: 42, title: "issue 42" });
  assert.equal(readIssue(42, "owner/repo", { run: () => ({ status: 1 }) }), null);

  // existingBeadFingerprints from externalRef and description
  const beadsMock = {
    status: 0,
    stdout: JSON.stringify([
      { id: "vb-1", status: "open", external_ref: `factory:${fp}` },
      { id: "vb-2", status: "closed", description: `Some details\nFingerprint: ${"2".repeat(64)}` },
    ]),
  };
  const beadMap = existingBeadFingerprints("/tmp/target", { run: () => beadsMock });
  assert.ok(beadMap.has(fp));
  assert.ok(beadMap.has("2".repeat(64)));
  assert.equal(existingBeadFingerprints("/tmp/target", { run: () => ({ status: 1 }) }), null);
});

test("suggestsFunctionalityChange detects signals in description or remediation", () => {
  assert.equal(suggestsFunctionalityChange({ remediation: "This is a breaking change to the schema", description: "" }), true);
  assert.equal(suggestsFunctionalityChange({ remediation: "Refactor the module", description: "" }), true);
  assert.equal(suggestsFunctionalityChange({ remediation: "Change the default timeout", description: "" }), true);
  assert.equal(suggestsFunctionalityChange({ remediation: "Migrate database tables", description: "" }), true);
  assert.equal(suggestsFunctionalityChange({ remediation: "Fix typo in variable name", description: "simple bug" }), false);
});

test("--json emits machine-readable plan without writing issues or beads", () => {
  const res = runCli({
    args: ["--json", "--report", "voicebox-docs-drift-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-docs-drift-delta.md": fixture("voicebox-docs-drift-delta.md") },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    const plan = JSON.parse(res.stdout);
    assert.equal(plan.length, 1);
    assert.equal(plan[0].action, "issue");
    assert.equal(plan[0].finding.agent, "docs-drift");
    assert.equal(plan[0].finding.rule_id, "stale-route-table");
    assert.equal(plan[0].finding.identity_source, "recomputed-and-verified");
    assert.equal(res.ghCalls.length, 0);
    assert.equal(res.bdCalls.length, 0);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("plan output is sanitised too: a CI log must never capture the raw finding title", () => {
  // The plan is printed to stdout, and in CI stdout is a log that cannot be un-published. The raw
  // title used to be printed here, which disclosed a credential the triage model had echoed into it.
  const canary = `sk-${"Q".repeat(24)}`;
  const home = homedir();
  const rewritten = fixture("voicebox-qa-station-delta.md").replace(
    "Folder chip assertion waits on a load-sensitive timeout",
    `Password leak ${canary} in ${home}/worktrees/private/secret.txt`,
  );
  const res = runCli({
    args: ["--report", "voicebox-qa-station-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-qa-station-delta.md": rewritten },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    assert.ok(!res.stdout.includes(canary), `the plan captured the raw credential: ${res.stdout}`);
    assert.ok(!res.stdout.includes(home), `the plan captured a home path: ${res.stdout}`);
    assert.match(res.stdout, /\[redacted:openai-key\]/, "the plan must show the masked form where the value was");
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("plan output shows derived text, not model prose, for a credential finding", () => {
  // The secret-scan station: a credential by construction, with a rule id that also carries a hint.
  // Rewriting a rule id on a normal fixture would (correctly) break its fingerprint and be skipped,
  // so this drives the real credential fixture rather than manufacturing one.
  const res = runCli({
    args: ["--report", "voicebox-secret-scan-delta.md", "--repo", "owner/voicebox"],
    reports: { "voicebox-secret-scan-delta.md": fixture("voicebox-secret-scan-delta.md") },
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    assert.ok(!res.stdout.includes("CANARY-fixture-not-a-real-credential"), `the plan captured model prose: ${res.stdout}`);
    assert.ok(!res.stdout.includes("Hard-coded API key committed"), "the model's title was printed");
    assert.match(res.stdout, /generic-api-key match at config\/example.env:12/);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("promotion asks bd for the id with --silent rather than parsing its prose", () => {
  // The first live promotion reported the TEMP DIRECTORY name: a regex over bd's human output matched
  // it inside the printed path. `--silent` is the fix, so assert the flag is what is used.
  const fp = "d".repeat(64);
  const res = runCli({
    args: ["--promote", "10", "--reviewed-by", "alice", "--apply", "--repo", "owner/voicebox"],
    stubGh: ghStubViewing(
      JSON.stringify({
        number: 10,
        state: "OPEN",
        title: "[factory/high] perf-review: stub",
        body: `<!-- factory-fingerprint: ${fp} -->\n<!-- factory-station: perf-review -->\n<!-- factory-severity: high -->\n<!-- factory-state: new -->`,
        comments: [{ body: "<!-- factory-review: alice -->" }],
      }),
    ),
  });
  try {
    const create = res.bdCalls.find((call) => call.startsWith("create"));
    assert.ok(create, `no create call: ${res.bdCalls.join(" | ")}`);
    assert.match(create, /--silent/, `bd create must not rely on parsing human output: ${create}`);
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("--report-dir triages a directory of delta reports", () => {
  const names = readdirSync(FIXTURES).filter((n) => n.endsWith("-delta.md"));
  const reports = Object.fromEntries(names.map((n) => [n, fixture(n)]));
  const res = runCli({
    args: ["--report-dir", "%PRIVATE%", "--repo", "owner/voicebox"],
    reports,
  });
  try {
    assert.equal(res.status, 0, res.stderr);
    for (const name of names) {
      assert.match(res.stdout, new RegExp(name.replace(/[.]/g, "\\.")));
    }
  } finally {
    rmSync(res.box, { recursive: true, force: true });
  }
});

test("CLI exits with code 1 on missing arguments or conflicting flags", () => {
  // Neither --report nor --report-dir
  const noReport = runCli({ args: ["--repo", "owner/voicebox"] });
  try {
    assert.equal(noReport.status, 1);
    assert.match(noReport.stderr, /one of --report or --report-dir is required/);
  } finally {
    rmSync(noReport.box, { recursive: true, force: true });
  }

  // Both --report and --report-dir
  const both = runCli({ args: ["--report", "a.md", "--report-dir", "dir", "--repo", "owner/voicebox"] });
  try {
    assert.equal(both.status, 1);
    assert.match(both.stderr, /--report and --report-dir are mutually exclusive/);
  } finally {
    rmSync(both.box, { recursive: true, force: true });
  }

  // Missing repo
  const noRepo = runCli({
    args: ["--report", "voicebox-qa-station-delta.md"],
    reports: { "voicebox-qa-station-delta.md": fixture("voicebox-qa-station-delta.md") },
    env: { VOICEBOX_FACTORY_REPO: null },
  });
  try {
    assert.equal(noRepo.status, 1);
    assert.match(noRepo.stderr, /--repo <owner\/name> \(or \$VOICEBOX_FACTORY_REPO\) is required/);
  } finally {
    rmSync(noRepo.box, { recursive: true, force: true });
  }

  // Unreadable report file
  const unreadable = runCli({
    args: ["--report", "nonexistent-delta.md", "--repo", "owner/voicebox"],
  });
  try {
    assert.equal(unreadable.status, 1);
    assert.match(unreadable.stderr, /not a readable file/);
  } finally {
    rmSync(unreadable.box, { recursive: true, force: true });
  }

  // Empty report-dir
  const emptyDir = runCli({
    args: ["--report-dir", "%PRIVATE%", "--repo", "owner/voicebox"],
    reports: {},
  });
  try {
    assert.equal(emptyDir.status, 2);
    assert.match(emptyDir.stderr, /no \*-delta\.md reports/);
  } finally {
    rmSync(emptyDir.box, { recursive: true, force: true });
  }
});
