#!/usr/bin/env node
/**
 * Factory findings triage (voicebox-beads-h1u0).
 *
 * The Software Factory writes its *full, unredacted* delta report with `--sink file`, because
 * `file` is the only sink that is not a publication boundary (`lib/embargo.py`:
 * `PRIVATE_SINKS = {"file"}`). Voicebox is a public repository, so every other sink — including
 * the factory's own `beads` sink — is a disclosure boundary that withholds `critical` and `high`
 * findings regardless of how harmless they look.
 *
 * That left an operational gap behind `voicebox-beads-algv`: the private report is the only place
 * a high-severity finding exists, and nothing carried it to the project board. This script is that
 * bridge, and it is deliberately narrow:
 *
 *   1. It reads ONE private report (or a private directory of them). A report path inside the
 *      repository working tree is REFUSED, so the unredacted text cannot be committed.
 *   2. It recomputes each finding's fingerprint exactly as the factory does and refuses to file
 *      one it cannot recompute — an unverified identity is a deferred finding, not a guess.
 *   3. It files a bead only for findings the disclosure policy allows, only through the
 *      published (sanitised) view, and never with a raw credential or attack payload in the body.
 *   4. It reuses the factory's own bead convention (`external-ref factory:<sha256>` plus a
 *      `Fingerprint:` line), so a bead filed here and a bead filed by the factory's `beads` sink
 *      dedupe against each other instead of duplicating.
 *   5. It never edits code. A finding whose remediation changes behaviour is filed BLOCKED with a
 *      `human-review` label and the single decision a human has to make.
 *
 * The rules this script enforces are mirrored, not invented, from the factory:
 *   - `lib/embargo.py`      — IDENTITY_CRITICAL_AGENTS, VALID_SEVERITIES, EMBARGOED_SEVERITIES,
 *                             fail-closed severity (missing/unknown is `critical`).
 *   - `lib/redaction.py`    — CREDENTIAL_AGENTS (`secret-scan`) ship a location, never a snippet;
 *                             every other string is masked with the same credential shapes.
 *   - `lib/findings.py`     — compute_fingerprint / normalize_path / normalize_text and the
 *                             `external-ref` + `Fingerprint:` dedupe convention.
 *
 * Mirrored copies drift, so each mirrored constant carries the upstream name it mirrors and the
 * test fixture is generated by the factory's own renderer rather than hand-written.
 */

import { createHash } from "node:crypto";
import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, resolve, sep } from "node:path";
import { spawnSync } from "node:child_process";

// ---------------------------------------------------------------------------------------------
// Mirrored policy constants (upstream module named in each comment)
// ---------------------------------------------------------------------------------------------

/** Mirrors `lib/redaction.py:CREDENTIAL_AGENTS`. A scanner candidate *is* a credential. */
export const CREDENTIAL_AGENTS = new Set(["secret-scan"]);

/** Mirrors `lib/embargo.py:IDENTITY_CRITICAL_AGENTS` = CREDENTIAL_AGENTS | {vuln-*, threat-model}. */
export const IDENTITY_CRITICAL_AGENTS = new Set([
  ...CREDENTIAL_AGENTS,
  "vuln-discovery",
  "vuln-verify",
  "vuln-triage",
  "threat-model",
]);

/** Mirrors `lib/embargo.py:VALID_SEVERITIES`. Anything else is not a severity. */
export const VALID_SEVERITIES = Object.freeze(["critical", "high", "medium", "low", "info"]);

/** Mirrors `lib/embargo.py:EMBARGOED_SEVERITIES` — never published to a public tracker. */
export const EMBARGOED_SEVERITIES = new Set(["critical", "high"]);

/** Mirrors `lib/findings.py:BEAD_EXTERNAL_REF_PREFIX`. */
export const BEAD_EXTERNAL_REF_PREFIX = "factory:";

/**
 * Station class per agent, discovered from `factory list` (22 stations, 2026-10-07) and grouped
 * by what a finding tells the reader: a disclosure (security), a product surface (ux/docs), a
 * measurement (perf/ops) or an engineering invariant (quality). The grouping is used in the bead
 * body and for the human-readable plan; it does NOT change the disclosure policy, which is
 * severity-and-identity based exactly like the factory's.
 */
export const STATION_CLASSES = Object.freeze({
  "secret-scan": "security",
  "vuln-discovery": "security",
  "vuln-verify": "security",
  "vuln-triage": "security",
  "deps-supply-chain": "security",
  "threat-model": "security",
  "qa-station": "quality",
  "test-gap": "quality",
  "log-check": "quality",
  "issue-triage": "quality",
  "pr-fixer": "quality",
  "docs-drift": "docs",
  "docs-write": "docs",
  "release-notes": "docs",
  "ui-ux-audit": "ux",
  "accessibility": "ux",
  "modern-web": "ux",
  "perf-review": "perf",
  "perf-hillclimb": "perf",
  "bundle-size": "perf",
  "memory-profile": "perf",
  "resilience": "ops",
});

/**
 * Deterministic hint that a remediation changes functionality rather than repairing it. This is a
 * HINT, never a decision: the analyst confirms with `--functionality-change <rule_id>`, and the
 * report only ever files such a finding BLOCKED with a `human-review` label.
 */
const FUNCTIONALITY_CHANGE_SIGNALS = [
  /\bbreaking\b/i,
  /\bchange(?:s|d)?\s+(?:the\s+)?(?:api|route|protocol|cli|schema|behaviou?r|default|contract)\b/i,
  /\b(?:rename|refactor|redesign)\b/i,
  /\bmigrat(?:e|ion)\b/i,
];

// Mirrors `lib/redaction.py:ALL_PATTERNS` (BLOCK + BARE + PATTERNS), same names and order.
const CREDENTIAL_SHAPES = [
  ["pem-block", /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g],
  ["openai-key", /sk-(?:proj-|live-|test-)?[A-Za-z0-9_-]{16,}/g],
  ["stripe-key", /(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{16,}/g],
  ["google-api-key", /AIza[0-9A-Za-z_-]{35}/g],
  ["google-oauth", /ya29\.[0-9A-Za-z_-]{20,}/g],
  ["gitlab-pat", /glpat-[A-Za-z0-9_-]{20,}/g],
  ["npm-token", /npm_[A-Za-z0-9]{36}/g],
  ["private-key", /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g],
  [
    "aws-access-key",
    /(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}/g,
  ],
  ["github-pat", /ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}/g],
  ["slack-token", /xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*/g],
  [
    "generic-api-key",
    /(?:api_key|apikey|secret|token|password)\s*[:=]\s*['"][a-zA-Z0-9_\-]{20,80}['"]/gi,
  ],
  ["jwt-token", /ey[A-Za-z0-9_-]{10,}\.ey[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g],
];

// ---------------------------------------------------------------------------------------------
// Mirrored helpers (lib/findings.py)
// ---------------------------------------------------------------------------------------------

/** Mirrors `lib/findings.py:normalize_path`. */
export function normalizePath(path) {
  if (typeof path !== "string") return "";
  return path.replace(/\\/g, "/").trim().replace(/^[./]+/, "");
}

/** Mirrors `lib/findings.py:normalize_text`. */
export function normalizeText(text) {
  if (text === null || text === undefined) return "";
  const value = typeof text === "string" ? text : String(text);
  return value.trim().replace(/\s+/g, " ");
}

/** Mirrors `lib/findings.py:compute_fingerprint` — sha256(agent:rule_id:path:snippet). */
export function computeFingerprint({ agent, ruleId, path, snippet }) {
  const key = `${agent}:${ruleId}:${normalizePath(path)}:${normalizeText(snippet)}`;
  return createHash("sha256").update(key, "utf8").digest("hex");
}

// ---------------------------------------------------------------------------------------------
// Mirrored sanitisation (lib/redaction.py)
// ---------------------------------------------------------------------------------------------

/** Mirrors `lib/redaction.py:mask_text` — mask anything credential-shaped, same labels. */
export function maskText(value) {
  if (typeof value !== "string") return value;
  let masked = value;
  for (const [name, pattern] of CREDENTIAL_SHAPES) {
    masked = masked.replace(pattern, `[redacted:${name}]`);
  }
  return masked;
}

/**
 * Mirrors `lib/redaction.py:redact_finding`. A credential agent's snippet never ships in any
 * form — it becomes a location, so an unrecognised credential format cannot slip through either.
 * Every other string is masked. Home paths are elided so a private report's location does not
 * ride along into a public tracker.
 */
export function sanitizeFinding(finding, { privateRoot } = {}) {
  const credentialClass = CREDENTIAL_AGENTS.has(finding.agent);
  const snippet = credentialClass
    ? `[withheld: credential-class agent — see the private report at ${finding.path}:${finding.lineNumber ?? "?"}]`
    : maskText(finding.snippet ?? "");
  const elide = (value) => {
    if (typeof value !== "string") return value;
    let out = maskText(value);
    const home = homedir();
    if (home) out = out.split(home).join("~");
    if (privateRoot) out = out.split(privateRoot).join("<private-report-dir>");
    // Any remaining absolute home-shaped path (a different operator's tree) is elided too.
    out = out.replace(/\/(?:home|Users)\/[A-Za-z0-9._-]+/g, "~");
    return out;
  };
  return {
    title: elide(finding.title ?? ""),
    description: elide(finding.description ?? ""),
    remediation: elide(finding.remediation ?? ""),
    snippet,
    path: elide(finding.path),
    lineNumber: finding.lineNumber,
  };
}

// ---------------------------------------------------------------------------------------------
// Report parsing (the factory's own delta renderer: lib/findings.py:_render_delta_report)
// ---------------------------------------------------------------------------------------------

const FINDING_HEADING = /^### \[([^\]]+)\]\s+(.*?)\s+\(`([a-z]+)`\)\s*$/;
const FIELD = /^- \*\*(Rule|Location|Fingerprint|Description|Snippet|Remediation)\*\*:\s*(.*)$/;

/** Parse the badge. `[HIGH]`, `[HIGH · routed CRITICAL]`, `[FALSE POSITIVE]`. */
export function parseBadge(badge) {
  const text = badge.trim();
  if (/^FALSE POSITIVE$/i.test(text)) return { falsePositive: true };
  const routed = text.match(/^(\S+)\s*·\s*routed\s+(\S+)$/i);
  if (routed) {
    return { reported: routed[1].trim().toLowerCase(), routed: routed[2].trim().toLowerCase() };
  }
  return { reported: text.toLowerCase() };
}

/**
 * Parse a factory delta report into finding records.
 *
 * `agent` is the station name. The report's own filename is `<target>-<agent>-delta.md`, so the
 * caller derives it from the name; it cannot be read from the body, and identity is what decides
 * whether a finding may be published at all — hence the refusal below rather than a default.
 */
export function parseReport(markdown, { agent } = {}) {
  if (!agent) throw new Error("parseReport: `agent` is required (derive it from <target>-<agent>-delta.md)");
  const lines = String(markdown).split(/\r?\n/);
  const target = (lines.find((l) => l.startsWith("# Software Factory Delta Report:")) ?? "")
    .replace("# Software Factory Delta Report:", "")
    .trim();
  const findings = [];
  let inSection = false;
  let current = null;
  const flush = () => {
    if (current) findings.push(finishFinding(current, agent));
    current = null;
  };
  for (const line of lines) {
    if (line.startsWith("## ")) {
      flush();
      inSection = line.trim() === "## Action Required: New & Regressed Findings";
      continue;
    }
    if (!inSection) continue;
    const heading = line.match(FINDING_HEADING);
    if (heading) {
      flush();
      current = { badge: heading[1], heading: heading[2], state: heading[3], fields: {} };
      continue;
    }
    if (!current) continue;
    const field = line.match(FIELD);
    if (field) {
      current.fields[field[1]] = field[2].trim();
      continue;
    }
    // A wrapped continuation of the previous field (long descriptions are one line in the
    // renderer today, but CRLF/editor rewrites must not silently truncate a finding).
    if (/^\s+\S/.test(line) && Object.keys(current.fields).length > 0) {
      const last = Object.keys(current.fields).pop();
      current.fields[last] = `${current.fields[last]} ${line.trim()}`;
    }
  }
  flush();
  return { target, agent, findings };
}

function unquote(value) {
  const text = (value ?? "").trim();
  const ticked = text.match(/^`(.*)`$/);
  return ticked ? ticked[1] : text;
}

function finishFinding(raw, agent) {
  const badge = parseBadge(raw.badge);
  // The reduced (step-summary) form renders the rule id in the heading and omits the `Rule`
  // field entirely: `### [HIGH · routed critical] `path-traversal` (`new`)`. Reading only the
  // field left these as `unclassified`, which is exactly the identity a deferred finding must
  // still report correctly.
  const headingTicked = raw.heading.match(/^`(.*)`$/);
  const ruleId = unquote(raw.fields.Rule) || (headingTicked ? headingTicked[1] : "unclassified");
  const location = unquote(raw.fields.Location);
  const locationMatch = location.match(/^(.*):(\d+|\?)$/);
  const path = locationMatch ? locationMatch[1] : location;
  const lineNumber = locationMatch ? locationMatch[2] : "?";
  const fingerprintFromReport = unquote(raw.fields.Fingerprint).replace(/\.\.\.$/, "");
  const snippet = unquote(raw.fields.Snippet ?? "");
  const finding = {
    agent,
    ruleId,
    path,
    lineNumber,
    state: raw.state,
    title: headingTicked ? headingTicked[1] : raw.heading,
    description: raw.fields.Description ?? "",
    snippet,
    remediation: raw.fields.Remediation ?? "",
    falsePositive: Boolean(badge.falsePositive),
    severityReported: badge.reported ?? null,
    severityRouted: badge.routed ?? null,
    fingerprintFromReport: fingerprintFromReport || null,
  };
  finding.identityCritical = IDENTITY_CRITICAL_AGENTS.has(agent);
  finding.className = STATION_CLASSES[agent] ?? "quality";
  // Effective severity mirrors `lib/embargo.py:effective_severity`, fail-closed: an identity
  // rule cannot be argued away by the model's label, and a missing or unknown label is
  // `critical` — never `medium`, which is the band public sinks publish.
  const routed = finding.severityRouted ?? finding.severityReported;
  finding.effectiveSeverity = finding.identityCritical
    ? "critical"
    : VALID_SEVERITIES.includes(routed)
      ? routed
      : "critical";
  // Identity is recomputable only when the report carried the fields the factory hashes.
  const canRecompute = Boolean(path) && Boolean(raw.fields.Snippet !== undefined);
  finding.fingerprint = canRecompute
    ? computeFingerprint({ agent, ruleId, path, snippet })
    : null;
  finding.identitySource = finding.fingerprint
    ? finding.fingerprintFromReport && finding.fingerprint.startsWith(finding.fingerprintFromReport)
      ? "recomputed-and-verified"
      : "recomputed-mismatch"
    : "unverifiable";
  return finding;
}

// ---------------------------------------------------------------------------------------------
// Policy: severity mapping, routing, bead construction
// ---------------------------------------------------------------------------------------------

/** Priority mapping. `critical`/`high` never reach a public board except as a deferred record. */
export function priorityFor(finding) {
  switch (finding.effectiveSeverity) {
    case "critical":
      return 1;
    case "high":
      return 1;
    case "medium":
      return 2;
    default:
      return 3;
  }
}

/** The deterministic functionality-change hint. A hint only; `--functionality-change` confirms. */
export function suggestsFunctionalityChange(finding) {
  const text = `${finding.remediation} ${finding.description}`;
  return FUNCTIONALITY_CHANGE_SIGNALS.some((pattern) => pattern.test(text));
}

/**
 * Decide what happens to one finding. This is the whole policy, in one place, so the doc and the
 * tests can point at it rather than re-describe it.
 *
 * Returned `action`:
 *   - `file`   — a sanitised public bead is allowed.
 *   - `defer`  — sensitive and embargoed: private escalation only, NO public bead.
 *   - `skip`   — not actionable (false positive, unchanged, unmapped state).
 *   - `blocked`— sanitised bead, filed BLOCKED with `human-review`: the remediation changes
 *                behaviour and a human decides whether it is wanted (never an auto-fix).
 */
export function routeFinding(finding, { confirmedFunctionalityChange = false, includeLow = false } = {}) {
  const reasons = [];
  if (finding.falsePositive) return { action: "skip", reasons: ["triaged false positive by the factory"] };
  if (finding.state === "unchanged") return { action: "skip", reasons: ["unchanged: already tracked"] };
  if (!["new", "regressed"].includes(finding.state)) {
    return { action: "skip", reasons: [`state \`${finding.state}\` is not an action state`] };
  }
  if (finding.identitySource === "unverifiable") {
    return {
      action: "defer",
      reasons: ["identity unverifiable: the report carried no recomputable fingerprint (reduced/step-summary form)"],
    };
  }
  if (finding.identitySource === "recomputed-mismatch") {
    return {
      action: "defer",
      reasons: [
        "identity mismatch: the recomputed fingerprint does not match the report's prefix — refusing to file under an unverified identity",
      ],
    };
  }
  if (EMBARGOED_SEVERITIES.has(finding.effectiveSeverity)) {
    // One decision, not two: an identity-critical agent is already forced to `critical` above
    // (`effective_severity` behaviour), so a separate identity branch here would be unreachable
    // — the identity belongs in the reason a human reads, not in a second check that can never
    // fire. Mutation testing is what showed the difference.
    if (finding.effectiveSeverity === "critical") {
      return {
        action: "defer",
        reasons: [
          finding.identityCritical
            ? `sensitive critical: identity-critical agent \`${finding.agent}\` routes as critical whatever the station labelled it, and critical detail is never published to a public tracker`
            : "critical severity is deferred for a human regardless of station class (fail-closed)",
        ],
      };
    }
    reasons.push("high severity from a non-sensitive station: filed sanitised at P1");
  }
  if (["low", "info"].includes(finding.effectiveSeverity) && !includeLow) {
    return { action: "skip", reasons: [`${finding.effectiveSeverity} is below the board band (pass --include-low to file at P3)`] };
  }
  const functionality = confirmedFunctionalityChange || suggestsFunctionalityChange(finding);
  if (functionality) {
    return {
      action: "blocked",
      reasons: [
        confirmedFunctionalityChange
          ? "the analyst confirmed this remediation changes functionality"
          : "the remediation reads as a functionality change",
        "human decides whether the behaviour change is wanted: filed BLOCKED with `human-review`, never auto-fixed",
      ],
    };
  }
  return { action: "file", reasons: reasons.length ? reasons : ["publishable band"] };
}

/** Build the bead the factory's own `beads` sink would build, plus this policy's priority/labels. */
export function buildBead(finding, verdict, { privateRoot, target } = {}) {
  const published = sanitizeFinding(finding, { privateRoot });
  const type = /vuln|secret/.test(finding.agent) ? "bug" : "task";
  const labels = ["factory", `station:${finding.agent}`, `class:${finding.className}`];
  if (verdict.action === "blocked") labels.push("human-review");
  if (finding.state === "regressed") labels.push("regression");
  const decision = verdict.action === "blocked" ? "\n\nDecision needed: confirm whether to change this behaviour (yes/no) and, if yes, file the change as its own bead." : "";
  const body = [
    `Factory \`${finding.agent}\` (${finding.className}) reported this finding; the full report stays private and only this sanitised summary is published.`,
    "",
    `Rule: ${maskText(finding.ruleId)}`,
    `Path: ${published.path}:${published.lineNumber ?? "?"}`,
    `Severity: ${finding.effectiveSeverity}${finding.severityReported && finding.severityReported !== finding.effectiveSeverity ? ` (reported as ${finding.severityReported} by the station; treated as ${finding.effectiveSeverity})` : ""}`,
    `State: ${finding.state}`,
    "",
    published.description ? `Description: ${published.description}` : "",
    published.remediation ? `Remediation: ${published.remediation}` : "",
    published.snippet ? `Snippet:\n${published.snippet}` : "",
    decision,
    `Fingerprint: ${finding.fingerprint}`,
    `External reference: ${BEAD_EXTERNAL_REF_PREFIX}${finding.fingerprint}`,
  ]
    .filter((line) => line !== "")
    .join("\n");
  const title = maskText(`[${finding.agent}] ${finding.title}`).slice(0, 120);
  return {
    title,
    description: body,
    type,
    priority: priorityFor(finding),
    labels,
    externalRef: `${BEAD_EXTERNAL_REF_PREFIX}${finding.fingerprint}`,
    fingerprint: finding.fingerprint,
    target: target ?? null,
  };
}

// ---------------------------------------------------------------------------------------------
// Private report location + refusal
// ---------------------------------------------------------------------------------------------

/** The private report root. Reports never live in the repository working tree. */
export function privateRootFromEnv(env = process.env) {
  if (env.VOICEBOX_FACTORY_PRIVATE_DIR) return resolve(env.VOICEBOX_FACTORY_PRIVATE_DIR);
  return join(homedir(), ".voicebox", "factory-reports");
}

/** True when `path` is inside `root` (after resolving symlinks as far as the path exists). */
export function isInside(path, root) {
  const real = (value) => {
    try {
      return realpathSync(value);
    } catch {
      // The target may not exist yet (a report dir); resolve the closest existing ancestor.
      let parent = dirname(resolve(value));
      const seen = [];
      while (!existsSync(parent) && dirname(parent) !== parent) {
        seen.push(basename(parent));
        parent = dirname(parent);
      }
      const base = existsSync(parent) ? realpathSync(parent) : resolve(parent);
      return join(base, ...seen.reverse(), basename(resolve(value)));
    }
  };
  const realPath = real(path);
  const realRoot = real(root);
  return realPath === realRoot || realPath.startsWith(realRoot.endsWith(sep) ? realRoot : realRoot + sep);
}

/**
 * Derive the station from `<target>-<agent>-delta.md`.
 *
 * The station is matched as a longest known suffix rather than split on the last hyphen: several
 * station names contain hyphens themselves (`docs-drift`, `vuln-discovery`, `deps-supply-chain`),
 * and a greedy `(.+)-([a-z0-9-]+)` split reads `voicebox-docs-drift-delta.md` as station `drift` —
 * an unknown station at best, and for a security station the wrong disclosure class. The station
 * list is the one `factory list` reports (`STATION_CLASSES`).
 */
export function agentFromReportName(file) {
  const base = basename(file).replace(/-delta\.md$/i, "");
  const matches = Object.keys(STATION_CLASSES).filter((station) => base === station || base.endsWith(`-${station}`));
  if (matches.length === 0) return null;
  return matches.sort((a, b) => b.length - a.length)[0];
}

// ---------------------------------------------------------------------------------------------
// Board I/O (bd) — dedupe mirrors lib/findings.py:_existing_bead_fingerprints
// ---------------------------------------------------------------------------------------------

const BEAD_FINGERPRINT_LINE = /Fingerprint:\s*([0-9a-f]{64})/g;

/** fingerprint -> [{id, status}] for every bead already carrying one, or null when unreadable. */
export function existingBeadFingerprints(target, { bd = "bd", run = spawnSync } = {}) {
  const res = run(bd, ["list", "--all", "--json", "-n", "0", "-C", target], {
    cwd: target,
    encoding: "utf8",
    timeout: 60000,
  });
  if (res.error || res.status !== 0) return null;
  let rows;
  try {
    rows = JSON.parse(res.stdout);
  } catch {
    return null;
  }
  if (!Array.isArray(rows)) return null;
  const index = new Map();
  for (const bead of rows) {
    const fingerprints = new Set();
    const ref = bead?.external_ref;
    if (typeof ref === "string" && ref.startsWith(BEAD_EXTERNAL_REF_PREFIX)) {
      fingerprints.add(ref.slice(BEAD_EXTERNAL_REF_PREFIX.length).trim());
    }
    if (typeof bead?.description === "string") {
      for (const match of bead.description.matchAll(BEAD_FINGERPRINT_LINE)) fingerprints.add(match[1]);
    }
    for (const fp of fingerprints) {
      const list = index.get(fp) ?? [];
      list.push({ id: String(bead.id ?? "?"), status: String(bead.status ?? "") });
      index.set(fp, list);
    }
  }
  return index;
}

/** Mirrors the factory's duplicate rule: an open match always wins; a closed one only if not regressed. */
export function isDuplicate(finding, existing) {
  const matches = existing?.get(finding.fingerprint) ?? [];
  if (matches.length === 0) return null;
  const open = matches.filter((m) => m.status !== "closed");
  if (open.length > 0) return { ids: open.map((m) => m.id), why: "open bead already tracks it" };
  if (finding.state !== "regressed") {
    return { ids: matches.map((m) => m.id), why: "a closed bead already tracked it and nothing regressed" };
  }
  return null;
}

// ---------------------------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------------------------

const USAGE = `Usage:
  node scripts/factory-triage.mjs --report <path> [options]
  node scripts/factory-triage.mjs --report-dir <dir> [options]

Reads a factory delta report written with \`--sink file\` and produces sanitised, actionable bead
specifications. The report path MUST be private (default root: $VOICEBOX_FACTORY_PRIVATE_DIR, else
~/.voicebox/factory-reports); a path inside this repository is refused.

Options:
  --report <path>              One private report (e.g. voicebox-qa-station-delta.md)
  --report-dir <dir>           Every *-delta.md in a private directory
  --target <path>              Repository the beads are filed in (default: this repo)
  --agent <name>               Override the station name (default: from <target>-<agent>-delta.md)
  --apply                      File the beads with \`bd create\` (default: plan only)
  --include-low                Also file low/info findings at P3 (default: below the board band)
  --functionality-change <rule|agent>
                               Confirm a functionality change for that rule id or station
  --json                       Machine-readable plan on stdout
  --private-root <dir>         Override the private report root
  --escalation-log <path>      Private JSONL of deferred findings (default: <private-root>/escalations.jsonl)
  --help

Exit codes:
  0  a plan was produced, or beads were filed
  1  usage or policy refusal (an in-repo report, an unreadable file, an unreadable board)
  2  nothing actionable: no findings in band, or every finding is already tracked`;

function parseArgs(argv) {
  const opts = {
    report: null,
    reportDir: null,
    target: null,
    agent: null,
    apply: false,
    includeLow: false,
    functionality: new Set(),
    json: false,
    privateRoot: null,
    escalationLog: null,
    help: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const next = () => {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith("--")) throw new Error(`${arg} requires a value`);
      i += 1;
      return value;
    };
    switch (arg) {
      case "--report": opts.report = next(); break;
      case "--report-dir": opts.reportDir = next(); break;
      case "--target": opts.target = next(); break;
      case "--agent": opts.agent = next(); break;
      case "--apply": opts.apply = true; break;
      case "--include-low": opts.includeLow = true; break;
      case "--functionality-change": opts.functionality.add(next()); break;
      case "--json": opts.json = true; break;
      case "--private-root": opts.privateRoot = next(); break;
      case "--escalation-log": opts.escalationLog = next(); break;
      case "--help": case "-h": opts.help = true; break;
      default: throw new Error(`unknown argument: ${arg}`);
    }
  }
  return opts;
}

/** Build the whole plan: what would be filed, deferred, skipped or blocked, and why. */
export function buildPlan(reportFiles, opts) {
  const entries = [];
  for (const file of reportFiles) {
    const agent = opts.agent ?? agentFromReportName(file);
    if (!agent) throw new Error(`${file}: cannot determine the station; pass --agent`);
    if (!STATION_CLASSES[agent]) throw new Error(`${file}: unknown station "${agent}" (see \`factory list\`)`);
    const markdown = readFileSync(file, "utf8");
    const report = parseReport(markdown, { agent });
    for (const finding of report.findings) {
      const confirmed = opts.functionality.has(finding.ruleId) || opts.functionality.has(finding.agent);
      const verdict = routeFinding(finding, { confirmedFunctionalityChange: confirmed, includeLow: opts.includeLow });
      const entry = { report: basename(file), target: report.target, finding, verdict };
      if (verdict.action === "file" || verdict.action === "blocked") {
        entry.bead = buildBead(finding, verdict, { privateRoot: opts.privateRoot, target: report.target });
      }
      entries.push(entry);
    }
  }
  return entries;
}

function describePlan(entries) {
  const out = [];
  const groups = { file: [], blocked: [], defer: [], skip: [] };
  for (const entry of entries) groups[entry.verdict.action].push(entry);
  out.push(`Plan: ${groups.file.length} to file · ${groups.blocked.length} to file BLOCKED (human review) · ${groups.defer.length} deferred (private escalation) · ${groups.skip.length} skipped`);
  for (const [action, label] of [["file", "FILE"], ["blocked", "FILE BLOCKED"], ["defer", "DEFER + escalate privately"], ["skip", "SKIP"]]) {
    for (const entry of groups[action]) {
      const { finding, verdict } = entry;
      const where = `${finding.agent} ${finding.ruleId} ${finding.path}:${finding.lineNumber}`;
      out.push(`  [${label}] P${priorityFor(finding)} ${finding.effectiveSeverity} ${where}  (${entry.report})`);
      out.push(`      ${finding.title}`);
      for (const reason of verdict.reasons) out.push(`      - ${reason}`);
    }
  }
  return out.join("\n");
}

function main(argv) {
  let opts;
  try {
    opts = parseArgs(argv);
  } catch (error) {
    process.stderr.write(`${error.message}\n\n${USAGE}\n`);
    return 1;
  }
  if (opts.help) {
    process.stdout.write(`${USAGE}\n`);
    return 0;
  }
  if (opts.report && opts.reportDir) {
    process.stderr.write("--report and --report-dir are mutually exclusive\n");
    return 1;
  }
  if (!opts.report && !opts.reportDir) {
    process.stderr.write(`one of --report or --report-dir is required\n\n${USAGE}\n`);
    return 1;
  }
  const repoRoot = resolve(opts.target ?? process.cwd());
  const privateRoot = resolve(opts.privateRoot ?? privateRootFromEnv());
  const gated = [];
  const candidates = opts.report
    ? [resolveReportPath(opts.report, privateRoot)]
    : readdirSync(opts.reportDir)
        .filter((n) => n.endsWith("-delta.md"))
        .map((n) => join(opts.reportDir, n));
  if (candidates.length === 0) {
    process.stderr.write(`${opts.reportDir}: no *-delta.md reports\n`);
    return 2;
  }
  for (const file of candidates) {
    if (!existsSync(file) || !statSync(file).isFile()) {
      process.stderr.write(`${file}: not a readable file\n`);
      return 1;
    }
    // The full report is unredacted. A path inside the repository working tree is refused
    // outright: one `git add -A` would publish every credential the report names.
    if (isInside(file, repoRoot)) {
      process.stderr.write(
        `refused: ${file} is inside the repository (${repoRoot}). The factory's file sink is the ` +
          `unredacted evidence trail — write it to the private root instead ` +
          `(default ${privateRootFromEnv()}).\n`,
      );
      return 1;
    }
    gated.push(file);
  }
  const plan = buildPlan(gated, { ...opts, privateRoot });
  const actionable = plan.filter((e) => e.verdict.action !== "skip");

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(plan.map(serialisablePlanEntry), null, 2)}\n`);
  } else {
    process.stdout.write(`${describePlan(plan)}\n`);
  }
  if (actionable.length === 0) return 2;

  if (!opts.apply) return 0;

  // ---- apply: dedupe against the board exactly like the factory's beads sink, then create ----
  const existing = existingBeadFingerprints(repoRoot);
  if (existing === null) {
    process.stderr.write("could not list existing beads to dedupe against: nothing filed\n");
    return 1;
  }
  const escalations = actionable
    .filter((e) => e.verdict.action === "defer")
    .map((e) => ({
      at: new Date().toISOString(),
      fingerprint: e.finding.fingerprint,
      agent: e.finding.agent,
      rule_id: e.finding.ruleId,
      path: `${e.finding.path}:${e.finding.lineNumber}`,
      severity: e.finding.effectiveSeverity,
      state: e.finding.state,
      title: e.finding.title,
      description: e.finding.description,
      remediation: e.finding.remediation,
      snippet: e.finding.snippet,
      reasons: e.verdict.reasons,
    }));
  let filed = 0;
  let duplicates = 0;
  for (const entry of actionable) {
    const { finding, verdict } = entry;
    if (verdict.action === "defer") continue; // private only
    const duplicate = isDuplicate(finding, existing);
    if (duplicate) {
      duplicates += 1;
      process.stdout.write(`duplicate: ${finding.fingerprint.slice(0, 16)} (${duplicate.why}: ${duplicate.ids.join(", ")}) — skipped\n`);
      continue;
    }
    const bead = entry.bead;
    const args = [
      "create",
      "--title", bead.title,
      "--description", bead.description,
      "--type", bead.type,
      "--priority", String(bead.priority),
      "--labels", bead.labels.join(","),
      "--external-ref", bead.externalRef,
      "-C", repoRoot,
    ];
    const res = spawnSync("bd", args, { cwd: repoRoot, encoding: "utf8", timeout: 60000 });
    if (res.error || res.status !== 0) {
      process.stderr.write(`bd create failed for ${finding.fingerprint.slice(0, 16)}: ${res.stderr || res.error}\n`);
      continue;
    }
    const id = (res.stdout.match(/[A-Za-z0-9_-]+-[a-z0-9]{4,}/) ?? [])[0];
    if (id) {
      existing.set(finding.fingerprint, [{ id, status: "open" }]);
      filed += 1;
      process.stdout.write(`filed: ${finding.fingerprint.slice(0, 16)} -> ${id}\n`);
      if (verdict.action === "blocked") {
        // BLOCKED carries the owner, the reason and the one next decision — a parked bead
        // that says nothing is a bead nobody can pick up.
        spawnSync("bd", ["update", id, "--status", "blocked", "-C", repoRoot], { cwd: repoRoot, timeout: 60000 });
        spawnSync(
          "bd",
          ["comment", id, "Blocked pending human review: this remediation changes functionality. Next decision: confirm yes/no, then file the change as its own bead.", "-C", repoRoot],
          { cwd: repoRoot, timeout: 60000 },
        );
      }
    } else {
      process.stderr.write(`bd create returned no bead id for ${finding.fingerprint.slice(0, 16)}\n`);
    }
  }
  if (escalations.length > 0) {
    const logPath = opts.escalationLog ?? join(privateRoot, "escalations.jsonl");
    const line = `${escalations.map((e) => JSON.stringify(e)).join("\n")}\n`;
    mkdirSync(dirname(logPath), { recursive: true, mode: 0o700 });
    appendFileSync(logPath, line, { mode: 0o600 });
    process.stdout.write(`escalated privately: ${escalations.length} finding(s) -> ${logPath} (never filed publicly)\n`);
  }
  process.stdout.write(`applied: ${filed} filed, ${duplicates} duplicate, ${escalations.length} escalated privately\n`);
  return filed > 0 || escalations.length > 0 ? 0 : 2;
}

/**
 * Resolve a `--report` argument. A bare filename is looked for in the private root, so
 * `--report voicebox-qa-station-delta.md` works from anywhere without putting the private
 * directory on the command line; an existing path is used as given.
 */
export function resolveReportPath(arg, privateRoot) {
  if (isAbsolute(arg)) return arg;
  const fromCwd = resolve(arg);
  if (existsSync(fromCwd)) return fromCwd;
  return join(privateRoot, arg);
}

function serialisablePlanEntry(entry) {
  return {
    report: entry.report,
    target: entry.target,
    action: entry.verdict.action,
    reasons: entry.verdict.reasons,
    finding: {
      agent: entry.finding.agent,
      rule_id: entry.finding.ruleId,
      path: entry.finding.path,
      line_number: entry.finding.lineNumber,
      state: entry.finding.state,
      severity: entry.finding.effectiveSeverity,
      severity_reported: entry.finding.severityReported,
      identity_critical: entry.finding.identityCritical,
      fingerprint: entry.finding.fingerprint,
      identity_source: entry.finding.identitySource,
    },
    bead: entry.bead ?? null,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = main(process.argv.slice(2));
}
