#!/usr/bin/env node
/**
 * Factory findings publisher (voicebox-beads-h1u0).
 *
 * The Software Factory writes its full, unredacted delta report with `--sink file`, because `file` is
 * the only sink that is not a publication boundary. Voicebox is a public repository, so the factory's
 * configuration withholds `critical` and `high` findings from a tracker — and `docs/25-factory-agent-proposal.md`
 * measured what that produced: zero publishable bead output, with the only interesting findings
 * disappearing into a private artefact.
 *
 * By decision recorded in `voicebox-beads-h1u0` this repository deliberately bypasses that embargo
 * for its own findings: every severity is published as a PUBLIC issue, the triage record is written
 * on the issue, and no bead is created from a scan at all. A bead exists only when a reviewer runs
 * the explicit `--promote <issue>` command afterwards.
 *
 * What keeps that safe is not the embargo, it is the sanitiser:
 *
 *   1. It reads ONE private report (or a private directory of them). A path inside the repository is
 *      REFUSED, so the unredacted text cannot be committed by accident.
 *   2. It recomputes each finding's fingerprint exactly as the factory does, refuses to publish one
 *      it cannot recompute (an unverified identity defeats dedupe), and never publishes the same
 *      finding twice.
 *   3. It publishes only the sanitised view: the factory's own credential shapes are masked, an
 *      identity-critical station's raw candidate is withheld entirely, and home/private paths are
 *      elided. No raw credential value reaches issue text.
 *   4. Promotion is a review decision with a name attached: `--promote <n> --reviewed-by <actor>`
 *      is the only code path that creates a bead, it dedupes against beads already carrying the
 *      fingerprint, and a functionality-changing finding becomes a BLOCKED bead with a
 *      `human-review` label.
 *   5. It never edits code. Nothing is auto-fixed; the only writes are `gh issue create`,
 *      `gh issue comment` and (on promotion) `bd create`/`bd update`.
 *
 * The rules this script enforces are mirrored, not invented, from the factory:
 *   - the embargo module (`embargo.py`) — IDENTITY_CRITICAL_AGENTS, VALID_SEVERITIES,
 *     EMBARGOED_SEVERITIES, and fail-closed severity (missing/unknown is `critical`).
 *   - the redaction module (`redaction.py`) — CREDENTIAL_AGENTS and the credential shapes.
 *   - `compute_fingerprint` / `normalize_path` / `normalize_text` and the bead `external-ref`
 *     convention (findings.py).
 *
 * Mirrored copies drift, so each mirrored constant names the upstream rule it mirrors and the test
 * fixtures are generated by the factory's own renderer rather than hand-written.
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, realpathSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join, resolve, sep } from "node:path";
import { spawnSync } from "node:child_process";

// ---------------------------------------------------------------------------------------------
// Mirrored policy constants (upstream module named in each comment)
// ---------------------------------------------------------------------------------------------

/**
 * Mirrors `lib/redaction.py:CREDENTIAL_RULE_HINTS` — the second, independent trigger. Either signal
 * can be absent, so a finding is credential-bearing when either one fires: a station that is not the
 * credential scanner can still report a matched key, and the rule id is scanner-controlled.
 */
export const CREDENTIAL_RULE_HINTS = Object.freeze(["key", "secret", "token", "credential", "password", "private"]);

/** Mirrors `lib/redaction.py:CREDENTIAL_AGENTS`. A scanner candidate *is* a credential. */
export const CREDENTIAL_AGENTS = new Set(["secret-scan"]);

/** Mirrors `lib/embargo.py:IDENTITY_CRITICAL_AGENTS` = CREDENTIAL_AGENTS | {vuln-*, threat-model}. */
export const IDENTITY_CRITICAL_AGENTS = new Set([
  ...CREDENTIAL_AGENTS,
  "vuln-discovery",
  "vuln-verify",
  "vuln-triage",
  "threat-model",
]);

/** Mirrors `lib/embargo.py:VALID_SEVERITIES`. Anything else is not a severity. */
export const VALID_SEVERITIES = Object.freeze(["critical", "high", "medium", "low", "info"]);

/** Mirrors `lib/embargo.py:EMBARGOED_SEVERITIES` — never published to a public tracker. */
export const EMBARGOED_SEVERITIES = new Set(["critical", "high"]);

/** Mirrors `lib/findings.py:BEAD_EXTERNAL_REF_PREFIX`. */
export const BEAD_EXTERNAL_REF_PREFIX = "factory:";

/**
 * Station class per agent, discovered from `factory list` (22 stations, 2026-10-07) and grouped
 * by what a finding tells the reader: a disclosure (security), a product surface (ux/docs), a
 * measurement (perf/ops) or an engineering invariant (quality). The grouping is used in the bead
 * body and for the human-readable plan; it does NOT change the disclosure policy, which is
 * severity-and-identity based exactly like the factory's.
 */
export const STATION_CLASSES = Object.freeze({
  "secret-scan": "security",
  "vuln-discovery": "security",
  "vuln-verify": "security",
  "vuln-triage": "security",
  "deps-supply-chain": "security",
  "threat-model": "security",
  "qa-station": "quality",
  "test-gap": "quality",
  "log-check": "quality",
  "issue-triage": "quality",
  "pr-fixer": "quality",
  "docs-drift": "docs",
  "docs-write": "docs",
  "release-notes": "docs",
  "ui-ux-audit": "ux",
  "accessibility": "ux",
  "modern-web": "ux",
  "perf-review": "perf",
  "perf-hillclimb": "perf",
  "bundle-size": "perf",
  "memory-profile": "perf",
  "resilience": "ops",
});

/**
 * Deterministic hint that a remediation changes functionality rather than repairing it. This is a
 * HINT, never a decision: the analyst confirms with `--functionality-change <rule_id>`, and the
 * report only ever files such a finding BLOCKED with a `human-review` label.
 */
const FUNCTIONALITY_CHANGE_SIGNALS = [
  /\bbreaking\b/i,
  /\bchange(?:s|d)?\s+(?:the\s+)?(?:api|route|protocol|cli|schema|behaviou?r|default|contract)\b/i,
  /\b(?:rename|refactor|redesign)\b/i,
  /\bmigrat(?:e|ion)\b/i,
];

// Mirrors `lib/redaction.py:ALL_PATTERNS` (BLOCK + BARE + PATTERNS), same names and order.
const CREDENTIAL_SHAPES = [
  ["pem-block", /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g],
  ["openai-key", /sk-(?:proj-|live-|test-)?[A-Za-z0-9_-]{16,}/g],
  ["stripe-key", /(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{16,}/g],
  ["google-api-key", /AIza[0-9A-Za-z_-]{35}/g],
  ["google-oauth", /ya29\.[0-9A-Za-z_-]{20,}/g],
  ["gitlab-pat", /glpat-[A-Za-z0-9_-]{20,}/g],
  ["npm-token", /npm_[A-Za-z0-9]{36}/g],
  ["private-key", /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/g],
  [
    "aws-access-key",
    /(?:A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}/g,
  ],
  ["github-pat", /ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}/g],
  ["slack-token", /xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*/g],
  [
    "generic-api-key",
    /(?:api_key|apikey|secret|token|password)\s*[:=]\s*['"][a-zA-Z0-9_\-]{20,80}['"]/gi,
  ],
  ["jwt-token", /ey[A-Za-z0-9_-]{10,}\.ey[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g],
];

// ---------------------------------------------------------------------------------------------
// Mirrored helpers (lib/findings.py)
// ---------------------------------------------------------------------------------------------

/** Mirrors `lib/findings.py:normalize_path`. */
export function normalizePath(path) {
  if (typeof path !== "string") return "";
  return path.replace(/\\/g, "/").trim().replace(/^[./]+/, "");
}

/** Mirrors `lib/findings.py:normalize_text`. */
export function normalizeText(text) {
  if (text === null || text === undefined) return "";
  const value = typeof text === "string" ? text : String(text);
  return value.trim().replace(/\s+/g, " ");
}

/** Mirrors `lib/findings.py:compute_fingerprint` — sha256(agent:rule_id:path:snippet). */
export function computeFingerprint({ agent, ruleId, path, snippet }) {
  const key = `${agent}:${ruleId}:${normalizePath(path)}:${normalizeText(snippet)}`;
  return createHash("sha256").update(key, "utf8").digest("hex");
}

// ---------------------------------------------------------------------------------------------
// Mirrored sanitisation (lib/redaction.py)
// ---------------------------------------------------------------------------------------------

/** Mirrors `lib/redaction.py:mask_text` — mask anything credential-shaped, same labels. */
export function maskText(value) {
  if (typeof value !== "string") return value;
  let masked = value;
  for (const [name, pattern] of CREDENTIAL_SHAPES) {
    masked = masked.replace(pattern, `[redacted:${name}]`);
  }
  return masked;
}

/**
 * The title text that may be shown *anywhere* — the issue, and the plan a CI log captures.
 *
 * The plan used to print the finding's raw title. That is the same leak the factory's own
 * `stdout_safe_report` exists to prevent: a terminal or a CI log has no way to be un-published, so a
 * credential the triage model echoed into a title would be disclosed by the triage run itself.
 */
export function displayTitle(finding, { privateRoot } = {}) {
  const published = sanitizeFinding(finding, { privateRoot });
  if (isCredentialFinding(finding)) {
    return `${maskText(finding.ruleId)} match at ${published.path}:${published.lineNumber ?? "?"}`;
  }
  return published.title;
}

/** Mirrors `lib/redaction.py:is_credential_finding`. */
export function isCredentialFinding(finding) {
  if (CREDENTIAL_AGENTS.has(finding.agent)) return true;
  const ruleId = String(finding.ruleId ?? "").toLowerCase();
  return CREDENTIAL_RULE_HINTS.some((hint) => ruleId.includes(hint));
}

/** Mirrors `lib/redaction.py:WITHHELD_NOTE`. */
export const WITHHELD_NOTE =
  "Published summaries withhold the matched value and the triage notes for credential findings. Note " +
  "that the local report is a working file, not a durable store: this ISSUE is the durable record, and " +
  "a matched credential has to be rotated rather than archived.";

/** Mirrors `lib/redaction.py:GENERIC_REMEDIATION`. */
export const GENERIC_REMEDIATION = "Rotate the credential, remove it from source, and re-run the scan.";

/**
 * Mirrors `lib/redaction.py:redact_finding`. A credential agent's snippet never ships in any
 * form — it becomes a location, so an unrecognised credential format cannot slip through either.
 * Every other string is masked. Home paths are elided so a private report's location does not
 * ride along into a public tracker.
 */
export function sanitizeFinding(finding, { privateRoot } = {}) {
  // Withheld for every identity-critical station, not only the credential scanner: a vulnerability
  // agent's candidate is an attack payload by construction, and this pipeline publishes at every
  // severity. `credentialClass` is kept for callers that need to know which rule fired.
  const credentialClass = CREDENTIAL_AGENTS.has(finding.agent);
  const withheld = IDENTITY_CRITICAL_AGENTS.has(finding.agent) || isCredentialFinding(finding);
  const elide = (value) => {
    if (typeof value !== "string") return value;
    let out = maskText(value);
    const home = homedir();
    if (home) out = out.split(home).join("~");
    if (privateRoot) out = out.split(privateRoot).join("<private-report-dir>");
    // Any remaining absolute home-shaped path (a different operator's tree) is elided too.
    out = out.replace(/\/(?:home|Users)\/[A-Za-z0-9._-]+/g, "~");
    return out;
  };
  // The notice names the location, so it is built from the ELIDED path. Interpolating the raw one
  // published the operator's home directory (or the private report dir) into a public issue body.
  const snippet = withheld
    ? `[withheld: matched value not published (${elide(finding.path)}:${finding.lineNumber ?? "?"})]`
    : elide(maskText(finding.snippet ?? ""));
  return {
    title: elide(finding.title ?? ""),
    description: elide(finding.description ?? ""),
    remediation: elide(finding.remediation ?? ""),
    snippet,
    path: elide(finding.path),
    lineNumber: finding.lineNumber,
  };
}

// ---------------------------------------------------------------------------------------------
// Report parsing (the factory's own delta renderer: lib/findings.py:_render_delta_report)
// ---------------------------------------------------------------------------------------------

const FINDING_HEADING = /^### \[([^\]]+)\]\s+(.*?)\s+\(`([a-z]+)`\)\s*$/;
const FIELD = /^- \*\*(Rule|Location|Fingerprint|Description|Snippet|Remediation)\*\*:\s*(.*)$/;

/** Parse the badge. `[HIGH]`, `[HIGH · routed CRITICAL]`, `[FALSE POSITIVE]`. */
export function parseBadge(badge) {
  const text = badge.trim();
  if (/^FALSE POSITIVE$/i.test(text)) return { falsePositive: true };
  const routed = text.match(/^(\S+)\s*·\s*routed\s+(\S+)$/i);
  if (routed) {
    return { reported: routed[1].trim().toLowerCase(), routed: routed[2].trim().toLowerCase() };
  }
  return { reported: text.toLowerCase() };
}

/**
 * Parse a factory delta report into finding records.
 *
 * `agent` is the station name. The report's own filename is `<target>-<agent>-delta.md`, so the
 * caller derives it from the name; it cannot be read from the body, and identity is what decides
 * whether a finding may be published at all — hence the refusal below rather than a default.
 */
export function parseReport(markdown, { agent } = {}) {
  if (!agent) throw new Error("parseReport: `agent` is required (derive it from <target>-<agent>-delta.md)");
  const lines = String(markdown).split(/\r?\n/);
  const target = (lines.find((l) => l.startsWith("# Software Factory Delta Report:")) ?? "")
    .replace("# Software Factory Delta Report:", "")
    .trim();
  const findings = [];
  let inSection = false;
  let current = null;
  const flush = () => {
    if (current) findings.push(finishFinding(current, agent));
    current = null;
  };
  for (const line of lines) {
    if (line.startsWith("## ")) {
      flush();
      inSection = line.trim() === "## Action Required: New & Regressed Findings";
      continue;
    }
    if (!inSection) continue;
    const heading = line.match(FINDING_HEADING);
    if (heading) {
      flush();
      current = { badge: heading[1], heading: heading[2], state: heading[3], fields: {} };
      continue;
    }
    if (!current) continue;
    const field = line.match(FIELD);
    if (field) {
      current.fields[field[1]] = field[2].trim();
      continue;
    }
    // A wrapped continuation of the previous field (long descriptions are one line in the
    // renderer today, but CRLF/editor rewrites must not silently truncate a finding).
    if (/^\s+\S/.test(line) && Object.keys(current.fields).length > 0) {
      const last = Object.keys(current.fields).pop();
      current.fields[last] = `${current.fields[last]} ${line.trim()}`;
    }
  }
  flush();
  return { target, agent, findings };
}

function unquote(value) {
  const text = (value ?? "").trim();
  const ticked = text.match(/^`(.*)`$/);
  return ticked ? ticked[1] : text;
}

function finishFinding(raw, agent) {
  const badge = parseBadge(raw.badge);
  // The reduced (step-summary) form renders the rule id in the heading and omits the `Rule`
  // field entirely: `### [HIGH · routed critical] `path-traversal` (`new`)`. Reading only the
  // field left these as `unclassified`, which is exactly the identity a deferred finding must
  // still report correctly.
  const headingTicked = raw.heading.match(/^`(.*)`$/);
  const ruleId = unquote(raw.fields.Rule) || (headingTicked ? headingTicked[1] : "unclassified");
  const location = unquote(raw.fields.Location);
  const locationMatch = location.match(/^(.*):(\d+|\?)$/);
  const path = locationMatch ? locationMatch[1] : location;
  const lineNumber = locationMatch ? locationMatch[2] : "?";
  const fingerprintFromReport = unquote(raw.fields.Fingerprint).replace(/\.\.\.$/, "");
  const snippet = unquote(raw.fields.Snippet ?? "");
  const finding = {
    agent,
    ruleId,
    path,
    lineNumber,
    state: raw.state,
    title: headingTicked ? headingTicked[1] : raw.heading,
    description: raw.fields.Description ?? "",
    snippet,
    remediation: raw.fields.Remediation ?? "",
    falsePositive: Boolean(badge.falsePositive),
    severityReported: badge.reported ?? null,
    severityRouted: badge.routed ?? null,
    fingerprintFromReport: fingerprintFromReport || null,
  };
  finding.identityCritical = IDENTITY_CRITICAL_AGENTS.has(agent);
  finding.className = STATION_CLASSES[agent] ?? "quality";
  // Effective severity mirrors `lib/embargo.py:effective_severity`, fail-closed: an identity
  // rule cannot be argued away by the model's label, and a missing or unknown label is
  // `critical` — never `medium`, which is the band public sinks publish.
  const routed = finding.severityRouted ?? finding.severityReported;
  finding.effectiveSeverity = finding.identityCritical
    ? "critical"
    : VALID_SEVERITIES.includes(routed)
      ? routed
      : "critical";
  // Identity is recomputable only when the report carried the fields the factory hashes.
  const canRecompute = Boolean(path) && Boolean(raw.fields.Snippet !== undefined);
  finding.fingerprint = canRecompute
    ? computeFingerprint({ agent, ruleId, path, snippet })
    : null;
  finding.identitySource = finding.fingerprint
    ? finding.fingerprintFromReport && finding.fingerprint.startsWith(finding.fingerprintFromReport)
      ? "recomputed-and-verified"
      : "recomputed-mismatch"
    : "unverifiable";
  return finding;
}

// ---------------------------------------------------------------------------------------------
// Policy: severity mapping, routing, publication
// ---------------------------------------------------------------------------------------------

/**
 * The declaration every published issue carries. The factory withholds `critical` and `high` from
 * a public tracker; this repository deliberately does not, and a deliberate bypass has to say so
 * on the artefact it affects rather than in a comment somewhere.
 */
export const PUBLICATION_DECLARATION = [
  "This issue was created by the repository's own findings publisher (`scripts/factory-triage.mjs`),",
  "which reads a full, unredacted factory delta report (written with `--sink file`) and publishes a",
  "sanitised summary.",
  "",
  "**Visibility: public, declared deliberately.** This repository is public, and it publishes its own",
  "factory findings at every severity — critical and high included. The factory's automatic embargo",
  "withholds those bands from a public tracker, so this controlled publisher bypasses the factory's",
  "public sinks on purpose, by decision recorded in `voicebox-beads-h1u0`: a high finding is visible",
  "here instead of vanishing into a private artefact. It is *not* claiming a private target.",
  "",
  "No literal credential value or key is ever published, whatever the finding's severity: the report is",
  "masked with the same credential shapes the factory masks, a credential finding publishes derived text",
  "only, and a security station's raw candidate is withheld entirely.",
  "",
  "No bead was created from the scan. This issue is the record until a reviewer converts it, and the",
  "publisher has no option that creates beads from a report.",
].join("\n");

/** Priority mapping, used when an issue is promoted to a bead (never at publish time). */
export function priorityFor(finding) {
  switch (finding.effectiveSeverity) {
    case "critical":
    case "high":
      return 1;
    case "medium":
      return 2;
    default:
      return 3;
  }
}

/** The deterministic functionality-change hint. A hint only; `--functionality-change` confirms. */
export function suggestsFunctionalityChange(finding) {
  const text = `${finding.remediation} ${finding.description}`;
  return FUNCTIONALITY_CHANGE_SIGNALS.some((pattern) => pattern.test(text));
}

/**
 * Decide what happens to one finding. The whole policy, in one place, so the doc and the tests point
 * at it instead of re-describing it.
 *
 * Returned `action`:
 *   - `issue` — publish a sanitised public issue. Every severity is published here by decision; an
 *               identity-critical station's raw candidate is withheld from the published text, but
 *               the finding itself is never withheld and never silently dropped.
 *   - `skip`  — not publishable as work (false positive, unchanged, below band).
 *
 * `humanReview` marks a finding whose remediation changes behaviour: the issue says so and a human
 * decides, and the bead is filed BLOCKED if the issue is ever promoted. The publisher never fixes
 * anything itself.
 */
export function routeFinding(finding, { confirmedFunctionalityChange = false, includeLow = false } = {}) {
  const reasons = [];
  if (finding.falsePositive) return { action: "skip", humanReview: false, reasons: ["triaged false positive by the factory"] };
  if (finding.state === "unchanged") return { action: "skip", humanReview: false, reasons: ["unchanged: already tracked"] };
  if (!["new", "regressed"].includes(finding.state)) {
    return { action: "skip", humanReview: false, reasons: [`state \`${finding.state}\` is not an action state`] };
  }
  if (finding.identitySource === "unverifiable") {
    return {
      action: "skip",
      humanReview: false,
      reasons: [
        "identity unverifiable: the report carried no recomputable fingerprint (reduced/step-summary form), so a reviewer could not dedupe it",
      ],
    };
  }
  if (finding.identitySource === "recomputed-mismatch") {
    return {
      action: "skip",
      humanReview: false,
      reasons: [
        "identity mismatch: the recomputed fingerprint does not match the report's prefix — publishing under an unverified identity would defeat dedupe",
      ],
    };
  }
  if (["low", "info"].includes(finding.effectiveSeverity) && !includeLow) {
    return {
      action: "skip",
      humanReview: false,
      reasons: [`${finding.effectiveSeverity} is below the published band (pass --include-low to publish it at priority P3)`],
    };
  }
  if (EMBARGOED_SEVERITIES.has(finding.effectiveSeverity)) {
    reasons.push(
      finding.identityCritical
        ? `identity-critical station \`${finding.agent}\`: routed ${finding.effectiveSeverity} and published deliberately, with the raw candidate withheld`
        : `${finding.effectiveSeverity} severity is published deliberately (the factory embargo would withhold it)`,
    );
  } else {
    reasons.push("publishable band");
  }
  const functionality = confirmedFunctionalityChange || suggestsFunctionalityChange(finding);
  if (functionality) {
    reasons.push(
      confirmedFunctionalityChange
        ? "the analyst confirmed this remediation changes functionality"
        : "the remediation reads as a functionality change",
      "a human decides whether the behaviour change is wanted; if this issue is promoted the bead is filed BLOCKED, and nothing is auto-fixed",
    );
  }
  // A security station's description and remediation are MODEL-AUTHORED prose, and this pipeline
  // publishes at every severity, so those words reach the public tracker with no human in between.
  // The finding is therefore flagged for human verification: the identity of the issue is enough for
  // a reader, but nobody should act on an unreviewed remediation, and promotion files it BLOCKED.
  const modelProse = IDENTITY_CRITICAL_AGENTS.has(finding.agent);
  if (modelProse) {
    reasons.push(
      "this station's prose is model-authored and is published unreviewed by policy, so the issue is flagged for human verification; a promoted bead is filed BLOCKED",
    );
  }
  return { action: "issue", humanReview: functionality || modelProse, reasons };
}

/** The machine-readable identity of a published issue, greppable in the body. */
export function markerFor(finding, verdict) {
  const lines = [
    `<!-- factory-fingerprint: ${finding.fingerprint} -->`,
    `<!-- factory-station: ${finding.agent} -->`,
    `<!-- factory-severity: ${finding.effectiveSeverity} -->`,
    `<!-- factory-state: ${finding.state} -->`,
  ];
  if (verdict.humanReview) lines.push("<!-- factory-human-review -->");
  return lines.join("\n");
}

/**
 * Post the review record on the issue.
 *
 * "Review before bead" is only real if the evidence is on the artefact the promotion reads, so the
 * reviewer writes their verdict here and `--promote` refuses without it.
 */
export function reviewComment(actor, notes) {
  return [
    `Reviewed by ${actor}.${notes ? `\n\n${notes}` : ""}`,
    "",
    "This issue may now be converted to a bead with `--promote`; the bead is BLOCKED if the finding",
    "was flagged as a functionality change, and nothing is implemented before that decision is recorded.",
    "",
    `<!-- factory-review: ${actor} -->`,
  ].join("\n");
}

/** Read the markers back off a published body. Used by promotion and by the tests. */
export function parseMarkers(body) {
  const read = (name) => {
    const match = String(body).match(new RegExp(`<!--\\s*factory-${name}:\\s*(.*?)\\s*-->`));
    return match ? match[1] : null;
  };
  return {
    fingerprint: read("fingerprint"),
    station: read("station"),
    severity: read("severity"),
    state: read("state"),
    humanReview: /<!--\s*factory-human-review\s*-->/.test(String(body)),
    promotedTo: (String(body).match(/<!--\s*factory-promoted:\s*(.*?)\s*-->/) ?? [])[1] ?? null,
    reviewedBy: (String(body).match(/<!--\s*factory-review:\s*(.*?)\s*-->/) ?? [])[1] ?? null,
    selfTest: /<!--\s*factory-self-test\s*-->/.test(String(body)),
  };
}

/**
 * Build the published issue. Every string here is the published view: masked, with the private
 * report path and home directories elided, and with a security station's raw candidate withheld.
 */
export function buildIssue(finding, verdict, { privateRoot, repo, selfTest = false } = {}) {
  const published = sanitizeFinding(finding, { privateRoot });
  // A credential finding publishes DERIVED TEXT ONLY, mirroring `lib/redaction.py:redact_finding`:
  // the triage model's own words cannot be checked for an echo of a value whose shape is unknown,
  // so its title, description and remediation are replaced by scanner-controlled facts. The
  // identity-critical rule is deliberately stricter than upstream here — a vulnerability agent's
  // candidate is an attack payload, and this pipeline publishes at every severity.
  const credential = isCredentialFinding(finding);
  // A credential finding's evidence block is refused as well. `identityCritical` alone was not
  // enough: a QUALITY station can raise a credential rule, and its snippet block then published the
  // withheld notice (and, before the fix above, the raw path) into a public issue.
  const refused = finding.identityCritical || credential;
  const location = `${published.path}:${published.lineNumber ?? "?"}`;
  if (credential) {
    published.title = displayTitle(finding, { privateRoot });
    published.description = `The deterministic scanner matched \`${maskText(finding.ruleId)}\` at \`${location}\`. ${WITHHELD_NOTE}`;
    published.remediation = GENERIC_REMEDIATION;
  }
  const humanReview = verdict.humanReview ? "[human-review] " : "";
  const title = maskText(`${humanReview}[factory/${finding.effectiveSeverity}] ${finding.agent}: ${published.title}`).slice(0, 150);
  const severityLine =
    finding.severityReported && finding.severityReported !== finding.effectiveSeverity
      ? `${finding.effectiveSeverity} (the station labelled it \`${finding.severityReported}\`; it routes as \`${finding.effectiveSeverity}\`${finding.identityCritical ? " because this station's candidates are security-sensitive by construction" : ""})`
      : finding.effectiveSeverity;
  const body = [
    `**Station**: \`${finding.agent}\` (${finding.className} class) · **Severity**: ${severityLine} · **State**: ${finding.state}`,
    `**Rule**: \`${maskText(finding.ruleId)}\` · **Location**: \`${published.path}:${published.lineNumber ?? "?"}\``,
    "",
    published.description ? `**What the station reported**\n\n${published.description}` : "",
    published.remediation ? `\n**Suggested remediation**\n\n${published.remediation}` : "",
    refused
      ? "\n**Raw candidate withheld.** This station's candidates are credentials or attack payloads by construction, so the raw value is not published here; the rule, location and remediation above identify it. The local report that held it is a working file rather than a durable store — this issue is the durable record, and a credential must be rotated, not archived."
      : published.snippet
        ? `\n**Evidence**\n\n\`\`\`\n${published.snippet}\n\`\`\``
        : "",
    "",
    "**Triage**",
    "",
    ...verdict.reasons.map((reason) => `- ${reason}`),
    `- Identity: \`${finding.fingerprint}\` (${finding.identitySource === "recomputed-and-verified" ? "recomputed here and verified against the report" : finding.identitySource})`,
    "",
    verdict.humanReview
      ? "**Human review required before any implementation.** This remediation changes functionality, so a human decides whether the change is wanted. If this issue is promoted to a bead, that bead is filed BLOCKED with `human-review` and carries the decision that is needed. Nothing is fixed automatically."
      : "",
    "<details>",
    "<summary>Publication policy and provenance</summary>",
    "",
    PUBLICATION_DECLARATION,
    "</details>",
    "",
    markerFor(finding, verdict),
    // A self-test is marked as one AT CREATION. It exists so the publisher can be driven end to end
    // without a synthetic finding ever being mistaken for work, and promotion refuses it.
    selfTest ? "<!-- factory-self-test -->" : "",
  ]
    .filter((line) => line !== "")
    .join("\n");
  return {
    title,
    body,
    // The labels this publisher would REQUEST. `fileIssues` filters them against the labels that
    // actually exist; plan mode cannot know that without a network call, so it reports intent.
    labels: chooseLabels(finding, verdict, null),
    fingerprint: finding.fingerprint,
    station: finding.agent,
    severity: finding.effectiveSeverity,
    humanReview: verdict.humanReview,
    url: `${repo ?? "?"}/issues/`,
  };
}

/**
 * The labels to request: only ones that already exist on the repository, because creating labels is
 * a repository-configuration change and not this script's business. The body markers are the
 * machine-readable record either way.
 */
export function chooseLabels(finding, verdict, knownLabels) {
  const preferred = [];
  if (finding.className === "security" || finding.className === "quality") preferred.push("bug");
  if (finding.className === "docs") preferred.push("documentation");
  if (finding.className === "ux" && finding.agent === "accessibility") preferred.push("accessibility");
  if (["perf", "ops", "ux"].includes(finding.className)) preferred.push("enhancement");
  if (verdict.humanReview) preferred.push("human-review");
  const known = knownLabels ? new Set(knownLabels) : null;
  return [...new Set(preferred)].filter((label) => (known ? known.has(label) : true));
}

// ---------------------------------------------------------------------------------------------
// Private report location + refusal
// ---------------------------------------------------------------------------------------------

/** The private report root. Reports never live in the repository working tree. */
export function privateRootFromEnv(env = process.env) {
  if (env.VOICEBOX_FACTORY_PRIVATE_DIR) return resolve(env.VOICEBOX_FACTORY_PRIVATE_DIR);
  return join(homedir(), ".voicebox", "factory-reports");
}

/** True when `path` is inside `root` (symlinks resolved as far as the path exists). */
export function isInside(path, root) {
  const real = (value) => {
    try {
      return realpathSync(value);
    } catch {
      // The target may not exist yet (a report dir); resolve the closest existing ancestor.
      let parent = dirname(resolve(value));
      const seen = [];
      while (!existsSync(parent) && dirname(parent) !== parent) {
        seen.push(basename(parent));
        parent = dirname(parent);
      }
      const base = existsSync(parent) ? realpathSync(parent) : resolve(parent);
      return join(base, ...seen.reverse(), basename(resolve(value)));
    }
  };
  const contained = (candidate, base) =>
    candidate === base || candidate.startsWith(base.endsWith(sep) ? base : base + sep);
  // BOTH the named path and the resolved target are checked. A symlink that lives inside the
  // repository and points at a private report resolves outside, so a realpath-only check would
  // accept it — and one `git add -A` would then commit the link to the unredacted report
  // (review of 929c559, Finding 3).
  const lexicalPath = resolve(path);
  const lexicalRoot = resolve(root);
  if (contained(lexicalPath, lexicalRoot)) return true;
  return contained(real(path), real(root));
}

/**
 * Derive the station from `<target>-<agent>-delta.md`.
 *
 * The station is matched as a longest known suffix rather than split on the last hyphen: several
 * station names contain hyphens themselves (`docs-drift`, `vuln-discovery`, `deps-supply-chain`),
 * and a greedy `(.+)-([a-z0-9-]+)` split reads `voicebox-docs-drift-delta.md` as station `drift` —
 * an unknown station at best, and for a security station the wrong disclosure class. The station
 * list is the one `factory list` reports (`STATION_CLASSES`).
 */
export function agentFromReportName(file) {
  const base = basename(file).replace(/-delta\.md$/i, "");
  const matches = Object.keys(STATION_CLASSES).filter((station) => base === station || base.endsWith(`-${station}`));
  if (matches.length === 0) return null;
  return matches.sort((a, b) => b.length - a.length)[0];
}

// ---------------------------------------------------------------------------------------------
// Board I/O — issues are read and written through `gh`; beads only through --promote
// ---------------------------------------------------------------------------------------------

function gh(args, { run = spawnSync, repo } = {}) {
  const full = repo ? [...args, "--repo", repo] : args;
  const res = run("gh", full, { encoding: "utf8", timeout: 60000 });
  return { status: res?.status ?? 1, stdout: res?.stdout ?? "", stderr: res?.stderr ?? "", error: res?.error };
}

/** fingerprint -> [{number, state}] for every issue the publisher filed before, or null. */
export function existingIssues(repo, { run = spawnSync } = {}) {
  const res = gh(["issue", "list", "--state", "all", "--json", "number,body,state", "--limit", "500"], { run, repo });
  if (res.error || res.status !== 0) return null;
  let rows;
  try {
    rows = JSON.parse(res.stdout);
  } catch {
    return null;
  }
  if (!Array.isArray(rows)) return null;
  const index = new Map();
  for (const row of rows) {
    // Both shapes are indexed. This publisher writes an HTML comment, but the factory's OWN
    // github-issues sink (lib/findings.py:887-897) writes a markdown line with the same digest — and
    // a dedupe that only understands its own marker would file a second public issue for one finding.
    for (const fingerprint of fingerprintsInBody(row?.body ?? "")) {
      const list = index.get(fingerprint) ?? [];
      list.push({ number: String(row.number ?? "?"), state: String(row.state ?? "") });
      index.set(fingerprint, list);
    }
  }
  return index;
}

/** An open issue always wins; a closed one wins unless the finding regressed. */
export function isIssueDuplicate(finding, existing) {
  // A row may carry the 16-hex prefix (a report in reduced form) or the full digest.
  const matches = existing?.get(finding.fingerprint) ?? existing?.get(String(finding.fingerprint).slice(0, 16)) ?? [];
  if (matches.length === 0) return null;
  const open = matches.filter((m) => m.state.toUpperCase() !== "CLOSED");
  if (open.length > 0) return { numbers: open.map((m) => m.number), why: "an open issue already tracks it" };
  if (finding.state !== "regressed") {
    return { numbers: matches.map((m) => m.number), why: "a closed issue already tracked it and nothing regressed" };
  }
  return null;
}

/**
 * Every fingerprint a body carries, in any shape this project's publishers use.
 *
 * `<target>-<station>` issues filed by `factory-triage` carry `<!-- factory-fingerprint: <digest> -->`;
 * issues filed by the factory's own github-issues sink carry `**Fingerprint**: \`<digest>\``. Both are
 * the same sha256, so dedupe reads both and neither publisher can duplicate the other's issue.
 */
export function fingerprintsInBody(body) {
  const text = String(body ?? "");
  const found = new Set();
  for (const match of text.matchAll(/<!--\s*factory-fingerprint:\s*([0-9a-f]{16,64})\s*-->/g)) found.add(match[1]);
  for (const match of text.matchAll(/\*\*Fingerprint\*\*:\s*`?([0-9a-f]{16,64})`?/g)) found.add(match[1]);
  return [...found];
}

/** Labels that exist on the repository, or null when the list cannot be read. */
export function knownLabels(repo, { run = spawnSync } = {}) {
  const res = gh(["label", "list", "--json", "name", "--limit", "200"], { run, repo });
  if (res.error || res.status !== 0) return null;
  try {
    const rows = JSON.parse(res.stdout);
    return Array.isArray(rows) ? rows.map((r) => String(r.name)) : null;
  } catch {
    return null;
  }
}

/** Read one issue for promotion. */
export function readIssue(number, repo, { run = spawnSync } = {}) {
  const res = gh(
    ["issue", "view", String(number), "--json", "number,title,body,state,url,labels,comments"],
    { run, repo },
  );
  if (res.error || res.status !== 0) return null;
  try {
    return JSON.parse(res.stdout);
  } catch {
    return null;
  }
}

/** fingerprint -> [{id, status}] for beads already carrying one, or null. */
export function existingBeadFingerprints(target, { bd = "bd", run = spawnSync } = {}) {
  const res = run(bd, ["list", "--all", "--json", "-n", "0", "-C", target], { cwd: target, encoding: "utf8", timeout: 60000 });
  if (res?.error || res?.status !== 0) return null;
  let rows;
  try {
    rows = JSON.parse(res.stdout);
  } catch {
    return null;
  }
  if (!Array.isArray(rows)) return null;
  const index = new Map();
  for (const bead of rows) {
    const fingerprints = new Set();
    const ref = bead?.external_ref;
    if (typeof ref === "string" && ref.startsWith(BEAD_EXTERNAL_REF_PREFIX)) fingerprints.add(ref.slice(BEAD_EXTERNAL_REF_PREFIX.length).trim());
    if (typeof bead?.description === "string") {
      for (const match of bead.description.matchAll(/Fingerprint:\s*([0-9a-f]{64})/g)) fingerprints.add(match[1]);
    }
    for (const fp of fingerprints) index.set(fp, (index.get(fp) ?? []).concat([{ id: String(bead.id ?? "?"), status: String(bead.status ?? "") }]));
  }
  return index;
}

/** The bead a promoted issue becomes: the reviewer's decision is part of its record. */
export function beadForPromotion({ finding, issue, reviewedBy, repo, issueNumber }) {
  const priority = priorityFor(finding);
  const labels = ["factory"];
  if (finding.humanReview) labels.push("human-review");
  const body = [
    `Promoted from the published factory issue (${repo}#${issueNumber}) by ${reviewedBy}.`,
    "",
    `Station: ${finding.station} · Severity: ${finding.severity} · Rule: ${finding.ruleId}`,
    `Issue: ${issue?.url ?? `${repo}#${issueNumber}`}`,
    `Fingerprint: ${finding.fingerprint}`,
    "",
    issue?.title ? `Title: ${issue.title}` : "",
    "",
    "The sanitised finding text lives on the issue (this bead deliberately does not copy it, so there is one place to correct).",
    finding.humanReview
      ? "\nDecision needed before implementation: a human must confirm whether this behaviour change is wanted. The bead is BLOCKED until that decision is recorded."
      : "",
  ]
    .filter((line) => line !== "")
    .join("\n");
  return {
    title: maskText(
      `[${finding.station}] ${(issue?.title ?? "").replace(/^\[human-review\]\s*/, "").replace(/^\[factory\/[a-z]+\]\s*[^:]*:\s*/, "")}`,
    ).slice(0, 200),
    description: body,
    type: /vuln|secret/.test(finding.station) ? "bug" : "task",
    priority,
    labels,
    externalRef: `${BEAD_EXTERNAL_REF_PREFIX}${finding.fingerprint}`,
    blocked: Boolean(finding.humanReview),
  };
}

// ---------------------------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------------------------

const USAGE = `Usage:
  node scripts/factory-triage.mjs --report <path> [--json]
  node scripts/factory-triage.mjs --report <path> --file-issues
  node scripts/factory-triage.mjs --promote <issue-number> --reviewed-by <actor> [--apply]
  node scripts/factory-triage.mjs --report <path> --comment <issue-number>

Reads a factory delta report written with \`--sink file\` and publishes a sanitised PUBLIC issue for
each actionable finding, at every severity, with the triage record on the issue. It never creates a
bead from a report: a bead exists only when a reviewer promotes a published issue.

Options:
  --report <path>              One private report (e.g. voicebox-qa-station-delta.md)
  --report-dir <dir>           Every *-delta.md in a private directory
  --file-issues                Publish the issues (default: plan only, nothing is written)
  --review <number>            Record a review verdict ON the issue (required before promotion)
  --reviewed-by <actor>        Who performed the review; required by --review
  --promote <number>           Convert a REVIEWED issue into a bead (the only bead path)
  --comment <number>           Append sanitised triage to an EXISTING issue (alias --issue-number)
                               Never creates an issue or a bead, and never edits the issue body
  --notes <text>               Notes to record with --review
  --allow-closed               With --promote/--comment: allow a closed issue (default: refused)
  --allow-foreign-target       Publish a report whose target is not the --repo repository
  --apply                      With --promote: actually create the bead
  --repo <owner/name>          Repository for issues (default: the origin remote, else gh's repo)
  --target <path>              Repository the bead is filed in (default: this repo)
  --agent <name>               Override the station (default: from <target>-<agent>-delta.md)
  --include-low                Also publish low/info findings
  --functionality-change <rule|agent>
                               Confirm a functionality change for that rule id or station
  --json                       Machine-readable plan on stdout
  --private-root <dir>         Override the private report root
  --help

Exit codes:
  0  a plan was produced, an issue was published, or a bead was created
  1  usage or policy refusal (an in-repo report, an unreadable file or board, a foreign target), or a
     publication/bead write that FAILED — a partial publication is never reported as success
  2  nothing actionable: no findings in band, every finding already published, or nothing new
     left to triage on the issue named by --comment`;

function parseArgs(argv) {
  const opts = {
    report: null, reportDir: null, target: null, agent: null, apply: false, includeLow: false,
    functionality: new Set(), json: false, privateRoot: null, fileIssues: false, promote: null,
    reviewedBy: null, repo: null, help: false, review: null, notes: null, selfTest: false, allowClosed: false,
    comment: null, allowForeignTarget: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const next = () => {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith("--")) throw new Error(`${arg} requires a value`);
      i += 1;
      return value;
    };
    switch (arg) {
      case "--report": opts.report = next(); break;
      case "--report-dir": opts.reportDir = next(); break;
      case "--target": opts.target = next(); break;
      case "--agent": opts.agent = next(); break;
      case "--apply": opts.apply = true; break;
      case "--file-issues": opts.fileIssues = true; break;
      case "--promote": opts.promote = next(); break;
      case "--review": opts.review = next(); break;
      case "--notes": opts.notes = next(); break;
      case "--self-test": opts.selfTest = true; break;
      case "--allow-foreign-target": opts.allowForeignTarget = true; break;
      case "--comment":
      case "--issue-number": opts.comment = next(); break;
      case "--allow-closed": opts.allowClosed = true; break;
      case "--reviewed-by": opts.reviewedBy = next(); break;
      case "--repo": opts.repo = next(); break;
      case "--include-low": opts.includeLow = true; break;
      case "--functionality-change": opts.functionality.add(next()); break;
      case "--json": opts.json = true; break;
      case "--private-root": opts.privateRoot = next(); break;
      case "--help": case "-h": opts.help = true; break;
      default: throw new Error(`unknown argument: ${arg}`);
    }
  }
  return opts;
}

/** Resolve a `--report` argument: a bare filename is looked for in the private root. */
export function resolveReportPath(arg, privateRoot) {
  if (isAbsolute(arg)) return arg;
  const fromCwd = resolve(arg);
  if (existsSync(fromCwd)) return fromCwd;
  return join(privateRoot, arg);
}

/** Build the whole plan: what would be published and why, plus what is skipped and why. */
export function buildPlan(reportFiles, opts) {
  const entries = [];
  const repoName = opts.repo ? String(opts.repo).split("/").pop().toLowerCase() : null;
  for (const file of reportFiles) {
    const agent = opts.agent ?? agentFromReportName(file);
    if (!agent) throw new Error(`${file}: cannot determine the station; pass --agent`);
    if (!STATION_CLASSES[agent]) throw new Error(`${file}: unknown station "${agent}" (see \`factory list\`)`);
    const report = parseReport(readFileSync(file, "utf8"), { agent });
    // A report names its own target, and `--report-dir` takes every report in a directory. Publishing
    // repo B's finding into repo A's tracker is silent and public, so the mismatch is a REFUSAL.
    if (repoName && !opts.allowForeignTarget) {
      const reported = String(report.target ?? "").split("/").pop().toLowerCase();
      if (reported && reported !== repoName) {
        throw new Error(
          `${basename(file)}: the report targets "${report.target}" but --repo is ${opts.repo}: refusing to publish another repository's finding here (pass --allow-foreign-target to force)`,
        );
      }
    }
    for (const finding of report.findings) {
      const confirmed = opts.functionality.has(finding.ruleId) || opts.functionality.has(finding.agent);
      const verdict = routeFinding(finding, { confirmedFunctionalityChange: confirmed, includeLow: opts.includeLow });
      const entry = {
        report: basename(file),
        target: report.target,
        finding,
        verdict,
        displayTitle: displayTitle(finding, { privateRoot: opts.privateRoot }),
      };
      if (verdict.action === "issue") {
        entry.issue = buildIssue(finding, verdict, {
          privateRoot: opts.privateRoot,
          repo: opts.repo,
          selfTest: opts.selfTest,
        });
      }
      entries.push(entry);
    }
  }
  return entries;
}

function describePlan(entries, { privateRoot } = {}) {
  const groups = { issue: [], skip: [] };
  for (const entry of entries) groups[entry.verdict.action].push(entry);
  const lines = [
    `Plan: ${groups.issue.length} to publish as issues · ${groups.skip.length} not published (each with a reason below)`,
  ];
  for (const [action, label] of [["issue", "PUBLISH ISSUE"], ["skip", "NOT PUBLISHED"]]) {
    for (const entry of groups[action]) {
      const { finding, verdict } = entry;
      const review = verdict.humanReview ? " [human-review]" : "";
      // Masked and elided like every other published surface: a rule id can carry a token the model
      // echoed, and a path can carry the operator's home directory. A CI log cannot be un-published.
      const published = sanitizeFinding(finding, { privateRoot });
      lines.push(
        `  [${label}] P${priorityFor(finding)} ${finding.effectiveSeverity} ${finding.agent} ${maskText(finding.ruleId)} ${published.path}:${published.lineNumber}${review}  (${entry.report})`,
      );
      lines.push(`      ${entry.displayTitle}`);
      for (const reason of verdict.reasons) lines.push(`      - ${reason}`);
    }
  }
  return lines.join("\n");
}

function serialisablePlanEntry(entry, { privateRoot } = {}) {
  // The JSON plan is an output surface too: it is captured by CI and read by other tools, so the
  // rule id and the path are sanitised here for the same reason they are on the terminal.
  const published = sanitizeFinding(entry.finding, { privateRoot });
  return {
    report: entry.report,
    target: entry.target,
    action: entry.verdict.action,
    human_review: entry.verdict.humanReview,
    reasons: entry.verdict.reasons,
    finding: {
      agent: entry.finding.agent,
      rule_id: maskText(entry.finding.ruleId),
      path: published.path,
      line_number: entry.finding.lineNumber,
      state: entry.finding.state,
      severity: entry.finding.effectiveSeverity,
      severity_reported: entry.finding.severityReported,
      identity_critical: entry.finding.identityCritical,
      fingerprint: entry.finding.fingerprint,
      identity_source: entry.finding.identitySource,
    },
    issue: entry.issue ?? null,
  };
}

/**
 * Every fingerprint already recorded by this mode on an issue, read from its COMMENTS.
 *
 * The marker lives in the comment rather than the body on purpose: an inbound issue stays inbound
 * (its body untouched) for the router that triages it, and this set is what stops a re-scan spamming
 * the thread with findings a reader has already been shown.
 */
export function triagedFingerprints(comments) {
  const seen = new Set();
  for (const comment of comments ?? []) {
    for (const match of String(comment?.body ?? "").matchAll(/<!--\s*factory-triage-comment:\s*([0-9a-f]{16,64})\s*-->/g)) {
      seen.add(match[1]);
    }
  }
  return seen;
}

/** The sanitised triage comment for findings not yet recorded on the issue. */
export function buildTriageComment(entries, { privateRoot, repo, issueNumber } = {}) {
  const stations = [...new Set(entries.map((e) => e.finding.agent))].join(", ");
  const parts = [
    `Factory triage for this issue (station${entries.length === 1 ? "" : "s"}: ${stations}).`,
    "",
    "Findings below come from a deterministic scan of this repository. They are recorded here rather than",
    "filed as separate issues: this issue is the thread a person already opened, and a second issue for",
    "the same subject would split the conversation.",
  ];
  for (const entry of entries) {
    const { finding, verdict } = entry;
    const published = sanitizeFinding(finding, { privateRoot });
    parts.push(
      "",
      `**${finding.agent}** · severity \`${finding.effectiveSeverity}\` · state \`${finding.state}\` · ${verdict.action === "issue" ? "publishable" : "not published as a new issue"}`,
      `- Rule \`${maskText(finding.ruleId)}\` at \`${published.path}:${published.lineNumber ?? "?"}\``,
      `- ${entry.displayTitle}`,
      ...verdict.reasons.map((reason) => `- ${reason}`),
      "",
      `<!-- factory-triage-comment: ${finding.fingerprint} -->`,
      `<!-- factory-station: ${finding.agent} -->`,
      `<!-- factory-severity: ${finding.effectiveSeverity} -->`,
      `<!-- factory-state: ${finding.state} -->`,
    );
  }
  parts.push(
    "",
    "<details>",
    "<summary>Publication policy and provenance</summary>",
    "",
    PUBLICATION_DECLARATION,
    "</details>",
  );
  return parts.join("\n");
}

/** Append triage to an EXISTING issue. Comment-only: no issue, no bead, no body edit. */
function commentOnIssue(number, repo, entries, { privateRoot, apply, allowClosed }) {
  const issue = readIssue(number, repo);
  if (!issue) {
    process.stderr.write(`could not read issue ${repo}#${number}\n`);
    return 1;
  }
  if (String(issue.state ?? "").toUpperCase() === "CLOSED" && !allowClosed) {
    process.stderr.write(`${repo}#${number} is closed: triage is recorded on open issues (pass --allow-closed to override)\n`);
    return 1;
  }
  const already = triagedFingerprints(issue.comments);
  const fresh = entries.filter((entry) => !already.has(entry.finding.fingerprint));
  if (fresh.length === 0) {
    process.stdout.write(`nothing new: all ${entries.length} finding(s) are already triaged on ${repo}#${number}\n`);
    return 2;
  }
  const body = buildTriageComment(fresh, { privateRoot, repo, issueNumber: number });
  if (!apply) {
    process.stdout.write(`would comment on ${repo}#${number} with ${fresh.length} finding(s) (${entries.length - fresh.length} already recorded)\n${body}\n`);
    return 0;
  }
  const res = gh(["issue", "comment", String(number), "--body", body], { repo });
  if (res.error || res.status !== 0) {
    process.stderr.write(`could not comment on ${repo}#${number}: ${res.stderr || res.error}\n`);
    return 1;
  }
  process.stdout.write(`triaged: ${fresh.length} finding(s) recorded on ${repo}#${number}\n`);
  return 0;
}

/** Publish one issue per actionable finding, with dedupe against the issues already filed. */
function fileIssues(entries, { repo, target }) {
  const existing = existingIssues(repo);
  if (existing === null) {
    process.stderr.write(`could not list existing issues in ${repo}: nothing published\n`);
    return 1;
  }
  const labels = knownLabels(repo);
  let published = 0;
  let duplicates = 0;
  // A refused publication is counted, not swallowed. `gh issue create` failing used to `continue`
  // and leave the run reporting success, so a CI job could pass while a finding was never filed.
  let failed = 0;
  for (const entry of entries) {
    if (entry.verdict.action !== "issue") continue;
    const { finding } = entry;
    const duplicate = isIssueDuplicate(finding, existing);
    if (duplicate) {
      duplicates += 1;
      process.stdout.write(`duplicate: ${finding.fingerprint.slice(0, 16)} (${duplicate.why}: #${duplicate.numbers.join(", #")}) — skipped\n`);
      continue;
    }
    const args = ["issue", "create", "--title", entry.issue.title, "--body", entry.issue.body];
    const chosen = chooseLabels(finding, entry.verdict, labels);
    if (chosen.length > 0) args.push("--label", chosen.join(","));
    const res = gh(args, { repo });
    if (res.error || res.status !== 0) {
      process.stderr.write(`issue create failed for ${finding.fingerprint.slice(0, 16)}: ${res.stderr || res.error}\n`);
      failed += 1;
      continue;
    }
    const url = (res.stdout.match(/https?:\/\/\S+/) ?? [])[0] ?? "(no url returned)";
    existing.set(finding.fingerprint, [{ number: url.split("/").pop(), state: "OPEN" }]);
    published += 1;
    process.stdout.write(`published: ${finding.fingerprint.slice(0, 16)} -> ${url}${chosen.length ? ` [${chosen.join(",")}]` : ""}\n`);
  }
  process.stdout.write(
    `issues: ${published} published, ${duplicates} duplicate${failed > 0 ? `, ${failed} FAILED` : ""}\n`,
  );
  // An incomplete publication is a failure, never "nothing to do": exit 2 would read as a clean run.
  if (failed > 0) return 1;
  return published > 0 ? 0 : 2;
}

/** The only path that creates a bead: an explicit, reviewed promotion of a published issue. */
function promote(opts, { repo, target }) {
  const number = String(opts.promote);
  const issue = readIssue(number, repo);
  if (!issue) {
    process.stderr.write(`could not read issue ${repo}#${number}\n`);
    return 1;
  }
  const markers = parseMarkers(issue.body ?? "");
  if (!markers.fingerprint) {
    process.stderr.write(`${repo}#${number} carries no factory fingerprint marker: refusing to promote an issue this publisher did not create\n`);
    return 1;
  }
  // The marker is posted as a COMMENT on the issue, so reading only the body missed it: the first
  // live promotion wrote a marker that its own guard could not see, which would have permitted a
  // second bead on the next promotion.
  const comments = Array.isArray(issue.comments) ? issue.comments : [];
  const promotedInComment = comments.map((c) => parseMarkers(c?.body ?? "").promotedTo).find(Boolean) ?? null;
  const promotedTo = markers.promotedTo ?? promotedInComment;
  if (promotedTo) {
    process.stderr.write(`${repo}#${number} was already promoted to ${promotedTo}: refusing to create a second bead\n`);
    return 1;
  }
  // Review evidence must be ON the issue. `--reviewed-by` is a cross-check, not the evidence: a name
  // typed at promotion time proves nothing about whether a review happened.
  const comments0 = Array.isArray(issue.comments) ? issue.comments : [];
  const reviewedBy =
    comments0.map((c) => parseMarkers(c?.body ?? "").reviewedBy).find(Boolean) ?? markers.reviewedBy;
  if (!reviewedBy) {
    process.stderr.write(
      `${repo}#${number} carries no review record: record one with \`--review <number> --reviewed-by <actor>\` before promoting\n`,
    );
    return 1;
  }
  if (opts.reviewedBy && opts.reviewedBy !== reviewedBy) {
    process.stderr.write(`--reviewed-by ${opts.reviewedBy} does not match the reviewer recorded on ${repo}#${number} (${reviewedBy}): refusing\n`);
    return 1;
  }
  // The marker is posted as a COMMENT (that is where a receipt belongs), so a body-only check misses
  // it: my own live self-test marker on issue #17 was invisible here and only the already-promoted
  // guard refused it. Both places are inspected now.
  const selfTest = markers.selfTest || comments.map((c) => parseMarkers(c?.body ?? "").selfTest).find(Boolean) === true;
  if (selfTest) {
    process.stderr.write(`${repo}#${number} is marked as a publisher self-test: refusing to promote a test issue\n`);
    return 1;
  }
  if (String(issue.state ?? "").toUpperCase() === "CLOSED" && !opts.allowClosed) {
    process.stderr.write(`${repo}#${number} is closed: a closed issue is not work to start (pass --allow-closed to override)\n`);
    return 1;
  }
  const severity = VALID_SEVERITIES.includes(markers.severity) ? markers.severity : "critical";
  const finding = {
    station: markers.station ?? "unknown",
    severity,
    // The routing value `priorityFor` reads. An unrecognised marker fails closed to `critical`,
    // matching how the badge is treated at publish time.
    effectiveSeverity: severity,
    state: markers.state ?? "new",
    humanReview: markers.humanReview,
    ruleId: (issue.body.match(/\*\*Rule\*\*:\s*`([^`]+)`/) ?? [])[1] ?? "unclassified",
    fingerprint: markers.fingerprint,
  };
  const existing = existingBeadFingerprints(target);
  if (existing === null) {
    process.stderr.write("could not list existing beads to dedupe against: nothing filed\n");
    return 1;
  }
  const matches = existing.get(markers.fingerprint) ?? [];
  if (matches.length > 0) {
    process.stderr.write(`${repo}#${number} is already tracked by ${matches.map((m) => m.id).join(", ")}: nothing filed\n`);
    return 1;
  }
  const bead = beadForPromotion({ finding, issue, reviewedBy, repo, issueNumber: number });
  process.stdout.write(
    `would file ${bead.type} P${bead.priority}${bead.blocked ? " (BLOCKED, human review)" : ""}: ${bead.title}\n  external-ref ${bead.externalRef}\n`,
  );
  if (!opts.apply) return 0;
  const res = spawnSync("bd", ["create", "--silent", "--title", bead.title, "--description", bead.description, "--type", bead.type, "--priority", String(bead.priority), "--labels", bead.labels.join(","), "--external-ref", bead.externalRef, "-C", target], { cwd: target, encoding: "utf8", timeout: 60000 });
  if (res.error || res.status !== 0) {
    process.stderr.write(`bd create failed: ${res.stderr || res.error}\n`);
    return 1;
  }
  // `--silent` prints the id alone. Parsing the human output with a pattern instead picked the
  // directory name out of the printed path on the first live promotion.
  const id = (res.stdout ?? "").trim().split(/\s+/).pop();
  if (!id || !/^[A-Za-z0-9_-]+$/.test(id)) {
    process.stderr.write(`bd create returned no usable bead id: ${JSON.stringify(res.stdout)}\n`);
    return 1;
  }
  if (bead.blocked) {
    spawnSync("bd", ["update", id, "--status", "blocked", "-C", target], { cwd: target, timeout: 60000 });
    spawnSync("bd", ["comment", id, "Blocked pending human review: this remediation changes functionality. Next decision: confirm yes/no, then file the change as its own bead.", "-C", target], { cwd: target, timeout: 60000 });
  }
  const comment = gh(["issue", "comment", number, "--body", `Promoted to bead \`${id}\` by ${reviewedBy}.${bead.blocked ? " The bead is BLOCKED pending the human review decision recorded on this issue." : ""}\n\n<!-- factory-promoted: ${id} -->`], { repo });
  if (comment.error || comment.status !== 0) {
    process.stderr.write(`warning: created ${id} but could not comment on the issue: ${comment.stderr}\n`);
  }
  process.stdout.write(`filed: ${markers.fingerprint.slice(0, 16)} -> ${id}\n`);
  return 0;
}

function main(argv) {
  let opts;
  try {
    opts = parseArgs(argv);
  } catch (error) {
    process.stderr.write(`${error.message}\n\n${USAGE}\n`);
    return 1;
  }
  if (opts.help) {
    process.stdout.write(`${USAGE}\n`);
    return 0;
  }
  const repo = opts.repo ?? process.env.VOICEBOX_FACTORY_REPO ?? null;
  const target = resolve(opts.target ?? process.cwd());
  if (repo === null) {
    process.stderr.write("--repo <owner/name> (or $VOICEBOX_FACTORY_REPO) is required: issues are published to a specific repository\n");
    return 1;
  }
  if (opts.review) {
    if (!opts.reviewedBy) {
      process.stderr.write("--review requires --reviewed-by <actor>: the record has to name the reviewer\n");
      return 1;
    }
    const issue = readIssue(opts.review, repo);
    if (!issue) {
      process.stderr.write(`could not read issue ${repo}#${opts.review}\n`);
      return 1;
    }
    const res = gh(["issue", "comment", String(opts.review), "--body", reviewComment(opts.reviewedBy, opts.notes)], { repo });
    if (res.error || res.status !== 0) {
      process.stderr.write(`could not record the review: ${res.stderr || res.error}\n`);
      return 1;
    }
    process.stdout.write(`recorded: ${repo}#${opts.review} reviewed by ${opts.reviewedBy}\n`);
    return 0;
  }
  if (opts.promote) return promote(opts, { repo, target });
  if (opts.report && opts.reportDir) {
    process.stderr.write("--report and --report-dir are mutually exclusive\n");
    return 1;
  }
  if (!opts.report && !opts.reportDir) {
    process.stderr.write(`one of --report or --report-dir is required\n\n${USAGE}\n`);
    return 1;
  }
  const privateRoot = resolve(opts.privateRoot ?? privateRootFromEnv());
  const candidates = opts.report
    ? [resolveReportPath(opts.report, privateRoot)]
    : readdirSync(opts.reportDir).filter((n) => n.endsWith("-delta.md")).map((n) => join(opts.reportDir, n));
  if (candidates.length === 0) {
    process.stderr.write(`${opts.reportDir}: no *-delta.md reports\n`);
    return 2;
  }
  for (const file of candidates) {
    if (!existsSync(file) || !statSync(file).isFile()) {
      process.stderr.write(`${file}: not a readable file\n`);
      return 1;
    }
    if (isInside(file, target)) {
      process.stderr.write(
        `refused: ${file} is inside the repository (${target}). The report is the unredacted evidence ` +
          `trail — write it to the private root instead (default ${privateRootFromEnv()}).\n`,
      );
      return 1;
    }
  }
  let plan;
  try {
    plan = buildPlan(candidates, { ...opts, privateRoot, repo });
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    return 1;
  }
  if (opts.json) {
    process.stdout.write(`${JSON.stringify(plan.map((entry) => serialisablePlanEntry(entry, { privateRoot: opts.privateRoot })), null, 2)}\n`);
  } else process.stdout.write(`${describePlan(plan, { privateRoot: opts.privateRoot })}\n`);
  if (opts.comment) {
    // Deliberately independent of `actionable`: a comment records every finding the scan produced,
    // including the ones that are not published as issues, because the reader of THIS issue asked a
    // question and a silently dropped finding would be invisible.
    return commentOnIssue(opts.comment, repo, plan, {
      privateRoot,
      apply: true,
      allowClosed: opts.allowClosed,
    });
  }
  const actionable = plan.filter((e) => e.verdict.action === "issue");
  if (actionable.length === 0) return 2;
  if (opts.fileIssues) return fileIssues(plan, { repo, target });
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = main(process.argv.slice(2));
}
